### ISSUE TITLE
Parameter binding

### ISSUE THREAD

**Issue by zhongjiewu** [influxdata/influxdb-client-java#106]
Does this client support client binding like `influxdb-java` libarary?

**Comment by bednar** [comment]
Hi @zhongjiewu 

Can you please share a bit more detail what feature do you want? [Bind parameters?](https://docs.influxdata.com/influxdb/v1.7/tools/api/#bind-parameters)

Regards

**Comment by zhongjiewu** [comment]
@bednar yes, similar to the one line influxdb-java repo to address this issue: https://github.com/influxdata/influxdb-java/issues/274

BTW, what's the difference between this repo and influxdb-java repo?

**Comment by bednar** [comment]
The API for v2 doesn't have bind parameters - see https://github.com/influxdata/influxdb/issues/16109. Our API allows to specify `extern` via [Query](https://github.com/influxdata/influxdb-client-java/blob/b89c5e8923bd380c6c5b62807a074bbdd411ac24/client/src/generated/java/com/influxdb/client/domain/Query.java#L37).

This client library is for InfluxDB 2 and InfluxDB 1.8.

**Comment by backbone87** [comment]
extern does not seem to work in 1.8 -> https://github.com/influxdata/influxdb/issues/17794
