### ISSUE TITLE
Performance bug. Info message in closable method: "Flushing any cached BatchWrites before shutdown."

### ISSUE THREAD

**Issue by raven2cz** [influxdata/influxdb-client-java#114]
Class AbstractWriteClient
    public void close() {
        LOG.log(Level.INFO, "Flushing any cached BatchWrites before shutdown.");

        autoCloseables.remove(this);

        processor.onComplete();

        flushPublisher.onComplete();
        tempBoundary.onComplete();
        eventPublisher.onComplete();

        waitToCondition(() -> finished.get(), DEFAULT_WAIT);
    }

is called in the closable try-resource statement!
From **WriteApiImpl** which is inherited from this class.
Info level has to be removed from this. It causes higher performance problem and log is not possible to process there are thousand these lines.

**Comment by bednar** [comment]
Hi @raven2cz,

You are right. The `INFO` level is unnecessary, so we will change it to `FINE` level.

Regards

**Comment by bednar** [comment]
Hi @raven2cz,

The issue is fixed in [1.9.0 milestone](https://github.com/influxdata/influxdb-client-java/milestone/12). 


If you would like to use a preview version use our snapshot build from repository: https://oss.sonatype.org/content/repositories/snapshots/

Regards
