### ISSUE TITLE
Give scala and kotlin clients their own user agent string

### ISSUE THREAD

**Issue by russorat** [influxdata/influxdb-client-java#118]
https://github.com/influxdata/influxdb-client-java/tree/master/client-scala/src/main/scala/com/influxdb/client/scala

https://github.com/influxdata/influxdb-client-java/tree/master/client-kotlin

is it possible to set the user agent to be `influxdb-client-scala` if they are using the scala client and `influxdb-client-kotlin` for the kotlin client?

**Comment by bednar** [comment]
Yes. We will fix it in upcoming release.
