### ISSUE TITLE
NullPointer when using WriteApi#writePoints(List<Point> points)

### ISSUE THREAD

**Issue by ZakShearman** [influxdata/influxdb-client-java#135]
__Steps to reproduce:__

1. Use specified code (WriteApi#writePoints(List<Point> points) or seemingly any write).
2. Run until your heart's content. See code under Actual Behaviour if line for line specifics are needed, there isn't much code.

__Expected behaviour:__
Points would be added to the database with no errors.

__Actual behaviour:__
Errors spat out for every single point that is attempted to be added https://pastebin.com/ejWUeRPA.
Code screenshots:
https://zak.pink/2020/07/Astonishing-Darwinsfox-8445.jpg
https://zak.pink/2020/07/Sparse-Mousebird-8446.jpg
(I group points for 30 seconds then send them to the database, however, the error also occurs when just running `writePoint#Point` immediately).

__Specifications:__
 - Client Version: Latest (1.10.0)
 - InfluxDB Version: Latest AFAIK (2.0.0 (f54848f))
 - Platform: InfluxDB running locally on Ubuntu 18.04, API running on Windows, Java on a Spigot server.

Thanks for any help in advance and let me know if I missed any info or you need more. 💜.

**Comment by bednar** [comment]
Hi @ZakShearman,

It is caused by missing measurement name. Specify measurement name when you creating `Point`:

```java
Point.measurement("my-measurement")
```

instead

```java
new Point()
```

Regards

**Comment by ZakShearman** [comment]
Thanks yh, that worked. Maybe make a measurement required in the constructor to make it clearer for other people, IDK.

Sorry for taking your time though.

**Comment by bednar** [comment]
@ZakShearman, Yeah I've prepare a PR to clarify this - https://github.com/influxdata/influxdb-client-java/pull/136
