### ISSUE TITLE
What params are supported for FluxConnectionOptions?

### ISSUE THREAD

**Issue by arjenzhou** [influxdata/influxdb-client-java#144]
There are no documents about the supported parameters`FluxConnectionOptions.Build`, including the auth token or user and password necessarily.

I have tried token and password, which is invalid.
<img width="930" alt="image" src="https://user-images.githubusercontent.com/23600703/90751650-fa7d9880-e308-11ea-81a6-b11563c8ddff.png">
<img width="904" alt="image" src="https://user-images.githubusercontent.com/23600703/90751671-02d5d380-e309-11ea-80ca-68b3ee0fd627.png">

**Comment by arjenzhou** [comment]
<img width="808" alt="image" src="https://user-images.githubusercontent.com/23600703/90751980-6829c480-e309-11ea-8aba-10eda7420146.png">

**Comment by bednar** [comment]
Hi @arjenzhou,

thanks for using our client.

The params supported by `FluxConnectionOptions` are described here: https://github.com/influxdata/influxdb-client-java/tree/master/client-legacy#client-connection-string

Regards

**Comment by bednar** [comment]
@rolincova, please add same options as in C# - https://github.com/influxdata/influxdb-client-csharp/tree/master/Client.Legacy#authenticate-requests

**Comment by arjenzhou** [comment]
@bednar 
Also, I found there no org and bucket to be chose while using username and password when `create` a `influxDBClient`.
<img width="600" alt="image" src="https://user-images.githubusercontent.com/23600703/90842398-bf737780-e391-11ea-9493-900db222a36f.png">
Is token the only way used in InfluxDB v2?

**Comment by bednar** [comment]
Yeah, the token is only used in InfluxDB v2. If you have an instance InfluxDB 1.8+, you could use compatibility endpoint. For detail see:

- https://github.com/influxdata/influxdb-client-java#influxdb-18-api-compatibility
- https://github.com/influxdata/influxdb-client-java/blob/master/examples/src/main/java/example/InfluxDB18Example.java#L37

**Comment by arjenzhou** [comment]
@bednar Thanks for your reply, but I am using InfluxDB v2.🤣

```java
    /**
     * Create an instance of the InfluxDB 2.0 client.
     *
     * @param url      the url to connect to the InfluxDB
     * @param username the username to use in the basic auth
     * @param password the password to use in the basic auth
     * @return client
     * @see InfluxDBClientOptions.Builder#url(String)
     */
    @Nonnull
    public static InfluxDBClient create(@Nonnull final String url,
                                        @Nonnull final String username,
                                        @Nonnull final char[] password) {

        InfluxDBClientOptions options = InfluxDBClientOptions.builder()
                .url(url)
                .authenticate(username, password)
                .build();

        return create(options);
    }
```

**Comment by bednar** [comment]
Ok, a documentation for InfluxDB v2 connection string is here: https://github.com/influxdata/influxdb-client-java/tree/master/client#client-connection-string

**Comment by bednar** [comment]
@arjenzhou The better choice is to use a `token` instead of `username` and `password`.

If you would like to use `username`, `password` with `bucket` and `org` then you could use something like this:

```java
InfluxDBClientOptions options = InfluxDBClientOptions.builder()
        .url("http://localhost:9999")
        .authenticate("my-username", "my-password".toCharArray())
        .bucket("my-bucket")
        .org("my-org")
        .build();

InfluxDBClient client = InfluxDBClientFactory.create(options);
```
