### ISSUE TITLE
WARNING: A connection to http://localhost:8086/ was leaked. Did you forget to close a response body?

### ISSUE THREAD

**Issue by funston** [influxdata/influxdb-client-java#146]
Seeing this WARNING frequently. Not clear where it's coming from.

 - Client Version: 1.11.0
 - InfluxDB Version:  2.0
 - Platform: Mac

**Comment by bednar** [comment]
Hi @funston,

Thanks for using our client.

Could you share a piece of how you use a client? Do you use `write`, `query` or `management` API?

Regards

**Comment by sdether** [comment]
Running into the same problem with any usage of the write API. Using it from scala, so i have to manually handle close, but that does not seem to help:
```
    val dbClient = InfluxDBClientFactory.create(
      config.url,
      config.user,
      config.password.toCharArray
    )
    val writeApi = dbClient.getWriteApi
    try {
      writeApi.writePoints(config.db, "tester", List(Point.measurement("test").addField("counter", 1)).asJava)
    } finally {
      writeApi.close()
    }
```
is always accompanied by
```
Sep 13, 2020 11:48:14 AM com.influxdb.client.internal.AbstractWriteClient close
INFO: Flushing any cached BatchWrites before shutdown.
Sep 13, 2020 11:48:14 AM okhttp3.internal.platform.Platform log
WARNING: A connection to http://host.docker.internal:8086/ was leaked. Did you forget to close a response body? To see where this was allocated, set the OkHttpClient logger level to FINE: Logger.getLogger(OkHttpClient.class.getName()).setLevel(Level.FINE);
```
in the logs. The point does get to influx just fine tho.

**Comment by bednar** [comment]
@sdether thanks for detail info

I am not able to simulate this warning, but after some investigation I was identify a glitch in our code base. I hope so that the issue will be fixed by #151.

Could you test the following `SNAPSHOT` version with fixed sources?

```XML
<dependency>
    <groupId>com.influxdb</groupId>
    <artifactId>influxdb-client-java</artifactId>
    <version>1.12.0.okhttp-SNAPSHOT</version>
</dependency>
```

```groovy
dependencies {
    compile "com.influxdb:influxdb-client-java:1.12.0.okhttp-SNAPSHOT"
}
```
- repository: https://oss.sonatype.org/content/repositories/snapshots/

Regards

**Comment by sdether** [comment]
@bednar Thanks. That fixes the leaked resource.

Unrelated to that issue, i looks like you changed some other dependency since the version we're using (1.8.0) because now get I get this warning on start-up:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by retrofit2.Platform (file:/Users/arne/.ivy2/cache/com.squareup.retrofit2/retrofit/jars/retrofit-2.9.0.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```
That happens both in your snapshot and in `1.11.0` (did not try 1.10.x or 1.9.x)

**Comment by bednar** [comment]
@sdether The warnings are not issues in client, but bug in JDK -please see the answer on StackOverflow - https://stackoverflow.com/a/61259233

**Comment by sdether** [comment]
Thanks. All good then. Will upgrade to `1.12.0` when fix gets merged.
