### ISSUE TITLE
Routing logging to slf4j or disabling it

### ISSUE THREAD

**Issue by sdether** [influxdata/influxdb-client-java#152]
Logging currently goes to STDERR despite the documentation saying that default is NONE. Ideally I'd like to provide an interceptor for logging to route it to slf4j, but short of that just being able to disable its logging would be great, since we're already handling the events and the additional logging to STDERR does not provide any benefit.

**Comment by russorat** [comment]
makes sense. in the meantime, maybe this comment can be adapted as a workaround? https://github.com/influxdata/influxdb-java/issues/443#issuecomment-385243941

**Comment by sdether** [comment]
@russorat 👍  let me give that a try

**Comment by sdether** [comment]
The `j.u.l` logging did just the trick. And then i can filter the extraneous logging via `logback.xml`
