### ISSUE TITLE
Kotlin examples are written in Java

### ISSUE THREAD

**Issue by fezu54** [influxdata/influxdb-client-java#155]
The client libraries page for Kotlin is the same as for Java. Also all examples are written in Java and not in Kotlin. Hence, I would suggest to either remove it or convert the examples into Kotlin

###### URL for relevant page?
http//167.114.231.105/client_libraries/libraries/kotlin/

**Comment by bednar** [comment]
Hi @kelseiv,

Do you mean these examples?

![Screenshot 2020-09-29 at 09 11 51](https://user-images.githubusercontent.com/455137/94525282-23604a00-0234-11eb-969a-8691c90c2487.png)


Regards

**Comment by bednar** [comment]
Closed due to missing info.
