### ISSUE TITLE
Improve Write Examples

### ISSUE THREAD

**Issue by bpair** [influxdata/influxdb-client-java#158]
__Proposal:__
For clients that write data every second the client will remain open. There should be some information about keeping a client open.

__Current behavior:__
The current examples show a client being created, some work being done, and then the client is closed. Secondly, there is no information about the difference between opening a client with a username/password  versus an auth token.  

__Desired behavior:__
Describe the scenario where a client remains open and the issues that could arise. Describe the differences (if there are any) between creating a client with a username/password versus an authorization token. Is one more performant? Will one work for a client that remains open and one doesn't?

**Comment by bednar** [comment]
Hi @bpair,

thanks for your proposal.

1/ I will prepare an example with long living writes.
2/ The preferred way is authorization by `token`. The `username/password` depends on HTTP basic and expire after configured [session-length](https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#session-length). I will update a javadoc to clarify that.

Regards

**Comment by bednar** [comment]
Hi @bpair,

Check this example - https://github.com/influxdata/influxdb-client-java/blob/master/examples/src/main/java/example/WriteDataEverySecond.java

Regards
