### ISSUE TITLE
FluxCsvParser should be specified  character encoding。

### ISSUE THREAD

**Issue by gemron** [influxdata/influxdb-client-java#162]
https://github.com/influxdata/influxdb-client-java/blob/97eea4ae644e8f0d876a70fbd6cb95bda6d79718/client-core/src/main/java/com/influxdb/query/internal/FluxCsvParser.java#L119

this line maybe  
`Reader reader = new InputStreamReader(bufferedSource.inputStream(),StandardCharsets.UTF_8);`

I feel that the character encoding should be specified as UTF-8.
 Because I found that the default encoding is GBK when the encoding is not specified on our windows server, the returned query Chinese characters appear garbled.

**Comment by bednar** [comment]
@gemron thanks, we will take a look

**Comment by gemron** [comment]
@bednar Ok， thank you for your efforts
