### ISSUE TITLE
/api/v2/delete has been disabled and returns a 501 Not implemented message

### ISSUE THREAD

**Issue by VaSmitka** [influxdata/influxdb-client-java#177]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. DeleteApi deleteApi = client.getDeleteApi();
2. deleteApi.delete(start, stop, "", "my-bucket", "my-org");

__Expected behavior:__
Remove records from DB.

__Actual behavior:__
InfluxException: com.influxdb.exceptions.NotImplementedException: Not implemented

__Specifications:__
 - Client Version: 1.13.0
 - InfluxDB Version: 2.0.1
 - JDK Version: 11
 - Platform: Win 10 64-bit

**Comment by bednar** [comment]
Hi @VaSmitka,

thanks for using our client.

**The `delete` API works only for the Influx Cloud instance.** 

In `InfluxDB OSS 2.0rc`, the delete with predicate API (/api/v2/delete) has been disabled and returns a 501 Not implemented message.

- see details: https://docs.influxdata.com/influxdb/v2.0/reference/syntax/delete-predicate/

Regards

**Comment by bednar** [comment]
Related issue: https://github.com/influxdata/influxdb/issues/19635

**Comment by bednar** [comment]
The issue influxdata/influxdb#19635 is fixed, please update InfluxDB to `2.0.3`. 

https://github.com/influxdata/influxdb/blob/master/CHANGELOG.md#v203-2020-12-14
