### ISSUE TITLE
query too slow when querying large amount of data

### ISSUE THREAD

**Issue by lonelyleaf** [influxdata/influxdb-client-java#182]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

query something like 
```
from(bucket:"waterstrategy")
	|> range(start:2020-11-25T16:00:00.000000000Z, stop:2020-11-26T16:00:00.000000000Z)
	|> filter(fn: (r) => r["_measurement"] == "c_0000000I_1#截污井COD")
```

the amount of point is just around 5000 or 6000.the client return the response too slow about 5s  or 10s.
And the code stucked in `AbstracQueryApi.query()`

```java
        if (asynchronously) {
            query.enqueue(callback);
        } else {

            Response<ResponseBody> response;
            try {
                response = query.execute();
               //will stucked here for few second!
                callback.onResponse(query, response);
            } catch (IOException e) {
                catchOrPropagateException(e, onError);
            }
        }
```

__Expected behavior:__
When I use postman or influxdb's dashboard，the result will be returned in 0.2s or 0.5s

__Specifications:__
 - Client Version: 1.13.0
 - InfluxDB Version: 2.0-rc
 - JDK Version: 11
 - Platform: linux

**Comment by bednar** [comment]
Hi @lonelyleaf,

the most performance critical part is parsing into Java Objects - especially to Dates. The Postman simply displays results without this overhead.

How your data looks like? 
Did you try exclude useless columns from your query? Something like: `|> drop(columns: ["_start", "_stop"]`?

Regards

**Comment by lonelyleaf** [comment]
> Hi @lonelyleaf,
> 
> the most performance critical part is parsing into Java Objects - especially to Dates. The Postman simply displays results without this overhead.
> 
> How your data looks like?
> Did you try exclude useless columns from your query? Something like: `|> drop(columns: ["_start", "_stop"]`?
> 
> Regards
Drop cloums didn't not help.And do not thought is the query's problem,I tried your go client with the same query,it's very fast too.

I tried to add breadk point and the stuck happen when wating for the raw response.

**Comment by bednar** [comment]
Did you find where is a glitch? Which piece of code causes the time degradation?

**Comment by lonelyleaf** [comment]
@bednar 

Not found yet.Even I write a stand alone main file below,the code is still slow.

```
package com.influxdb;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.InfluxDBClientOptions;
import com.influxdb.client.QueryApi;
import com.influxdb.query.FluxRecord;
import com.influxdb.query.FluxTable;
import com.influxdb.query.dsl.Flux;
import com.influxdb.query.dsl.functions.FilterFlux;
import com.influxdb.query.dsl.functions.restriction.Restrictions;

import java.time.Duration;
import java.time.ZonedDateTime;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Collectors;

public class Main {

    public static void main(String[] args) {
        String bucket = "waterstrategy";
        String org = "waterstrategy";

        InfluxDBClientOptions.Builder builder = InfluxDBClientOptions.builder()
                .bucket(bucket)
                .org(org)
                .url("XXX")
                .authenticateToken("XXX".toCharArray());

        InfluxDBClient client = InfluxDBClientFactory.create(builder.build());
        client.disableGzip();

        QueryApi queryApi = client.getQueryApi();

        Restrictions restrictions = Restrictions.measurement().equal("test1");

        ZonedDateTime start = ZonedDateTime.now().minusDays(2);
        FilterFlux flux = Flux.from(bucket)
                .range(start.toInstant())
                .filter(restrictions);

        ZonedDateTime queryStart = ZonedDateTime.now();
        List<FluxTable> tables = queryApi.query(flux.toString());
        ZonedDateTime queryStop = ZonedDateTime.now();
        Duration between = Duration.between(queryStart, queryStop);
        System.out.println("influxdb query spend:" + between.toString());
        List<FluxRecord> records = tables.stream()
                .flatMap(fluxTable -> fluxTable.getRecords().stream())
                .collect(Collectors.toList());

        System.out.println(records.size());
    }

}

```

The out put
```
influxdb query spend:PT8.4313757S
38238
```

**Comment by bednar** [comment]
I don't think so that is caused by OkHttp interceptors. Would you describe your data and how much data do you want retrieve? I will use it to check the client performance.

**Comment by lonelyleaf** [comment]
@bednar this is out simluation data about 2day,now to get these in java client we'll spend about 5-7s.In influxdb's consul it's just 0.3s.

```
from(bucket: "waterstrategy")
  |> range(start: 2020-12-02T00:00:00Z, stop: 2020-12-03T00:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "c_0000000I_1#截污井雨量")
```

[2020-12-03-17-19_chronograf_data.zip](https://github.com/influxdata/influxdb-client-java/files/5634977/2020-12-03-17-19_chronograf_data.zip)

**Comment by lonelyleaf** [comment]
@bednar Any good new about this problem?

**Comment by bednar** [comment]
Hi @lonelyleaf, currently not :(. I hope so that I will have enough time to look at this at end of week

**Comment by antoinedvd** [comment]
@bednar @lonelyleaf I pretty sure this issue is due to the gzip issue 😉     
For me, the gain is significant. I made a lot of tests with a huge amount of data, on average the response time is divided by 2 to 3.
- [PR 205](https://github.com/influxdata/influxdb-client-java/pull/205)
- [Issue Comment](https://github.com/influxdata/influxdb-client-java/issues/50#issuecomment-796896401)

**Comment by bednar** [comment]
Hi @lonelyleaf,

I tried querying your data by following code:

```java
package example;

import java.time.Duration;
import java.time.ZonedDateTime;
import java.util.List;
import java.util.stream.Collectors;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.InfluxDBClientOptions;
import com.influxdb.client.QueryApi;
import com.influxdb.query.FluxRecord;
import com.influxdb.query.FluxTable;

public class SynchronousQuery {

    public static void main(final String[] args) {

        String url = "http://localhost:9999";
        String token = "my-token";
        String org = "my-org";
        String bucket = "my-bucket";

        InfluxDBClientOptions.Builder builder = InfluxDBClientOptions.builder()
                .authenticateToken(token.toCharArray())
                .url(url)
                .org(org)
                .bucket(bucket);

        InfluxDBClient client = InfluxDBClientFactory
                .create(builder.build())
                .enableGzip();

        String query = "from(bucket: \"my-bucket\")\n"
                + " |> range(start: 2020-12-02T00:00:00Z, stop: 2020-12-03T00:00:00Z)\n"
                + " |> filter(fn: (r) => r[\"_measurement\"] == \"c_0000000I_1#截污井雨量\")\n"
                + " |> drop(columns: [\"_start\", \"_stop\"])";

        QueryApi queryApi = client.getQueryApi();

        ZonedDateTime queryStart = ZonedDateTime.now();
        List<FluxTable> tables = queryApi.query(query);
        ZonedDateTime queryStop = ZonedDateTime.now();

        Duration between = Duration.between(queryStart, queryStop);
        System.out.println("influxdb query spend:" + between.toString());

        List<FluxRecord> records = tables.stream()
                .flatMap(fluxTable -> fluxTable.getRecords().stream())
                .collect(Collectors.toList());

        System.out.println(records.size());
    }
}
```

and results are fine:
```
influxdb query spend:PT0.873324S
39772
```

**Specifications**:

Client Version: 2.1.0
InfluxDB Version: 2.0.4 (` docker run --detach --publish 8086:8086  influxdb:latest`)
JDK Version: openjdk-11.0.2.jdk
Platform: macOS
Heap Size: 256.0 MB
Heap Max Size: 4.0 GB

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
