### ISSUE TITLE
Missing tail function

### ISSUE THREAD

**Issue by CalamarBicefalo** [influxdata/influxdb-client-java#189]
__Proposal:__
Add [tail function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/tail/).

__Current behavior:__
There's no tail function although it works just fine in influxdb.

__Desired behavior:__
Use tail function with the DSL.

__Alternatives considered:__
Strings instead of the flux DSL.

__Use case:__
Queries with tail

**Comment by bednar** [comment]
Hi @CalamarBicefalo,

thanks for the issue, we will take a look.

As a workaround you could use something like:

```java
Flux flux = Flux
	.from("telegraf")
	.range(-33L, ChronoUnit.HOURS)
	.expression("tail()");
```

Regards

**Comment by CalamarBicefalo** [comment]
Neat! was wondering if there was a string fallback! thanks @bednar !
