### ISSUE TITLE
Pushdown functions

### ISSUE THREAD

**Issue by CalamarBicefalo** [influxdata/influxdb-client-java#190]
__Proposal:__
Improve documentation to indicate which are pushdown functions and which not

__Current behavior:__
There's no indication at all of whether a function is pushdown or not.

__Desired behavior:__
Clear documentation stating whether a function will be executed in memory or in the database, or links to documentation where this is categorised by DB version.

__Alternatives considered:__
Check the DB docs, which are vague at best. 

Most functions are not indicated as neither pushdown nor memory intensive, leaving one wonder whether the query will explode soon enough. E.g.: 1.8 suggests group is pushdown, 2.0 suggests it isn't and the docs state "We’re continually optimizing Flux and this list may not represent its current state." so having in mind greater versions have degraded functions from pushdown to non-pushdown and the docs warn you the list might not apply anymore it is hard to understand what's pushdown and whatnot.

__Use case:__
Make sure we can write queries that perform reasonably well

**Comment by bednar** [comment]
Hi @CalamarBicefalo,

Which functions do you mean? Functions from `FluxDSL`? 

And also pull requests are always welcome 😉 

Regards

**Comment by CalamarBicefalo** [comment]
Hey @bednar , I'd be very happy to issue a PR with improved docs for this particular issue if we agree on a way forward. 

The problem I am finding is influxdb docs aren't too clear about what are and aren't pushdown functions. E.g. If I want to get the latest 10 records and I do something that involves a very wide range (because I do not know the range upfront) followed by filter, sort and limit. Will sort and limit behave as pushdown? 

The docs in 1.8 say only group, range and filter are pushdown. In 2.0 it says only range and filter. In both cases the docs suggest the list may not be up to date.

If we could clarify this, I'd be happy to try and give it a shot.

**Comment by bednar** [comment]
I am not expert to Flux, but according to the docs only the `filter` is pushdown function. https://docs.influxdata.com/influxdb/cloud/query-data/optimize-queries/#pushdown-functions

We have a #flux channel in our community Slack. Try to ask here:

https://influxcommunity.slack.com/archives/CH8RGRW4T

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
