### ISSUE TITLE
WriteApi for Kotlin Client missing?

### ISSUE THREAD

**Issue by a-mesin** [influxdata/influxdb-client-java#194]
Hi, 

the Kotlin Client docs is saying "The reference Kotlin client that allows query and **write** for the InfluxDB 2.0 by Kotlin Channel coroutines."

I can't seem to find any info about the WriteAPI in the sources. Is it not implemented yet?

**Comment by bednar** [comment]
Hi @a-mesin, 

thanks for using our client.

We currently don't have implemented the write API in Kotlin. I hope so that we will have an enough time to implemented soon.

Could you describe your requirements? It will help us to implement what users want.

Regards
