### ISSUE TITLE
Any plan for reactor operation support

### ISSUE THREAD

**Issue by AtticusLv** [influxdata/influxdb-client-java#195]
is there any plan for Reactor support?
https://projectreactor.io/

**Comment by bednar** [comment]
Hi @AtticusLv,

thanks for your issue.

We have the `influxdb-client-reactive` version of our client - https://github.com/influxdata/influxdb-client-java/tree/master/client-reactive#influxdb-client-reactive. It is based on `RxJava`.

The `Reactor` has supports for `RxJava`. See - https://projectreactor.io/docs/adapter/release/api/reactor/adapter/rxjava/RxJava2Adapter.html

Regards

**Comment by AtticusLv** [comment]
Thanks!
