### ISSUE TITLE
Licensing issue with JSON-Java library

### ISSUE THREAD

**Issue by hakandilek** [influxdata/influxdb-client-java#196]
__Proposal:__

[JSON-Java dependency](https://github.com/stleary/JSON-java) does not have a free license. This can be exchanged by [Jackson](https://github.com/FasterXML/jackson).

__Current behavior:__

Currently `influxdb-client-core` depends on the [JSON-Java library](https://github.com/stleary/JSON-java).
![image](https://user-images.githubusercontent.com/1072473/106734302-27054280-6613-11eb-9763-653223558b19.png)

__Desired behavior:__

JSON-Serialization function in [AbstractQueryApi](https://github.com/influxdata/influxdb-client-java/blob/02039edb7805e56b74b0a837c19eb4a1d6fcd705/client-core/src/main/java/com/influxdb/internal/AbstractQueryApi.java#L77) (client-core) can be exchanged with an alternative implementation using [Jackson](https://github.com/FasterXML/jackson)

__Alternatives considered:__

Jackson is the most commonly used (de)serialization library. No other alternative considered.

__Use case:__

Due to the [license terms](https://github.com/stleary/JSON-java/blob/master/LICENSE) of `json-java`, JSON License does not count as a free software license. The sentence in license terms "The Software shall be used for Good, not Evil." is relative for interpretation and bounding it's usage. This definition [does not fit](https://opensource.org/faq#evil) into free/open-source software definition.

**Comment by bednar** [comment]
Hi @hakandilek, thanks for issue. We will take a look.

The `influxdb-client-java` depends on `com.google.code.gson` so we could consider to use it instead of `json-20200518`.

**Comment by hakandilek** [comment]
Thank you for for the quick fix. This is great and above my expectation.  👏🏅
