### ISSUE TITLE
Error：create a bucket 

### ISSUE THREAD

**Issue by marryfeng** [influxdata/influxdb-client-java#209]
question：com.influxdb.exceptions.BadRequestException', 'failed to unmarshal json: id must have a length of 16 bytes

I make sure my token and org  are correct ,But ,when I create a bucket，it will occur the question.

**Comment by bednar** [comment]
Hi @marryfeng,

thanks for using our client. 

It looks like that you are using `organization name` instead of `organization ID`. Try to use something like:

```java
Organization organization = client.getOrganizationsApi()
        .findOrganizations().stream()
        .filter(it -> "my-org".equals(it.getName()))
        .findFirst()
        .orElseThrow(IllegalStateException::new);

Bucket temperatureBucket = client
        .getBucketsApi()
        .createBucket("new-bucket", organization);
```

Regards

**Comment by marryfeng** [comment]
thank you very much !

**Comment by marryfeng** [comment]
this question has been resolved!
