### ISSUE TITLE
How to make dynamic query

### ISSUE THREAD

**Issue by HDK7** [influxdata/influxdb-client-java#212]
Hi,
I want to make dynamic query

now I am using like this :

```
        if (search.getSensorId() == null && search.getContainerId() != null) {
            if(search.getClassCode() != null){
                restriction = Restrictions.and(
                        Restrictions.tag("containerId").equal(search.getContainerId()),
                        Restrictions.tag("classCode").equal(search.getClassCode()),
                        Restrictions.measurement().equal("data")
                );
            }else {
                restriction = Restrictions.and(
                        Restrictions.tag("containerId").equal(search.getContainerId()),
                        Restrictions.measurement().equal("data")
                );
            }
        }
```

is there any better way?

------------------------
p.s
Whenever I call influx reading method, I close  influxDBClient. is it right way? 
Our project is going to have a lot of traffic.

```
@controller
public class Controller{
     public ClassA method(){
         private InfluxDBClient influxDBClient = InfluxDBClientFactory.create(connectionUrl, token.toCharArray(), orgId);
         ...
        
         List<ClassA> results = queryApi.query(flux.toString(), ClassA.class);
         influxConnectService.close();        
     }
}
```

**Comment by bednar** [comment]
> Hi,
> I want to make dynamic query
> 
> now I am using like this :
> 
> ```
>         if (search.getSensorId() == null && search.getContainerId() != null) {
>             if(search.getClassCode() != null){
>                 restriction = Restrictions.and(
>                         Restrictions.tag("containerId").equal(search.getContainerId()),
>                         Restrictions.tag("classCode").equal(search.getClassCode()),
>                         Restrictions.measurement().equal("data")
>                 );
>             }else {
>                 restriction = Restrictions.and(
>                         Restrictions.tag("containerId").equal(search.getContainerId()),
>                         Restrictions.measurement().equal("data")
>                 );
>             }
>         }
> ```
> 
> is there any better way?

Currently not. I will improve our `FluxDSL`, so you will be able to do something like:

```java
String classCode = search.getClassCode();
restriction = Restrictions.and(
        Restrictions.tag("containerId").equal(search.getContainerId()),
        classCode != null ? Restrictions.tag("classCode").equal(classCode) : Restrictions.or(),
        Restrictions.measurement().equal("data")
);
```

Stay tuned.

> p.s
> Whenever I call influx reading method, I close influxDBClient. is it right way?
> Our project is going to have a lot of traffic.
> 
> ```
> @controller
> public class Controller{
>      public ClassA method(){
>          private InfluxDBClient influxDBClient = InfluxDBClientFactory.create(connectionUrl, token.toCharArray(), orgId);
>          ...
>         
>          List<ClassA> results = queryApi.query(flux.toString(), ClassA.class);
>          influxConnectService.close();        
>      }
> }
> ```

You can use the `InfluxDBClient` and the `QueryApi` as a singleton and close the client when you disposing your app.

**Comment by HDK7** [comment]
Thank you very much. your comments are very helpful for me. My questions are all solved.
