### ISSUE TITLE
Add supporting for custom Enum in FluxResultMapper in `toPOJO` method

### ISSUE THREAD

**Issue by Khakov** [influxdata/influxdb-client-java#217]
Using enum as a name of tags is a very often case, mapping POJO to InfluxDb works perfectly, but in reverse case it doesn't

I did not check, but it looks as working code (need to check):
```
...
if (fieldType.isEnum()) {
		field.set(object, Enum.valueOf((Class<Enum>) fieldType, value));
                return;
}
...
```

**Comment by bednar** [comment]
@Khakov, thanks for issue 👍, is this something you might be willing to help with?

**Comment by bednar** [comment]
#218 is ready to review, stay tuned
