### ISSUE TITLE
has Client considered the connection pool？

### ISSUE THREAD

**Issue by aohanhe** [influxdata/influxdb-client-java#225]
Our system may have multiple threads writing data. Do I recreate the client for each write operation? Is there a performance problem? and if I create only one client per thread, sometimes there will be no data to write for a long time. Will this client object can work?
thanks!

**Comment by bednar** [comment]
Hi @aohanhe,

sorry for the late. 

> Our system may have multiple threads writing data. Do I recreate the client for each write operation? Is there a performance problem? 

No, You should use the `InfluxDBClient` as a singleton in multiple threads. There are two APIs for write data into InfluxDB:

- `WriteApi` - supports underlaying batching, success and error response are propagated via events - https://github.com/influxdata/influxdb-client-java/tree/master/client#handle-the-events 
- `WriteApiBlocking` - directly write data into database, error response are directly propagated as an exception

> and if I create only one client per thread, sometimes there will be no data to write for a long time. Will this client object can work?

Yes, it will be work. There is a underlaying connection pool in `OkHttpClient`.

> thanks!

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
