### ISSUE TITLE
Retrofit2 Removes characters after hostname.

### ISSUE THREAD

**Issue by webstersteele** [influxdata/influxdb-client-java#226]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behaviour.

1. behaviour can be reproduced with the following code snippet: 

```
FluxClient fluxClient = FluxClientFactory.create("http://exampleurl.com/influxDB/");

        String flux = "from(bucket:\"test_bucket/hour\")\n" +
                "        |> range(start:-5m)";

        List<FluxTable> tables = fluxClient.query(flux);
```

__Expected behavior:__
Describe what you expected to happen.

The flux client should query `http://exampleurl.com/influxDB/api/v2/query` and return the results of the query.

__Actual behavior:__
Describe What actually happened.

The fluxClient returns a `com.influxdb.exceptions.NotFoundException` but upon debugging, we can see the response actually looks like `Response{protocol=http/1.1, code=404, message=Not Found, url=http://exampleurl.com/api/v2/query}`

Therefore the `/InfluxDB` was cut off of the baseURL.

__Specifications:__
 - Client Version: 2.2.0
 - InfluxDB Version: 1.8
 - JDK Version: V8 u251
 - Platform: Mac (Mojave)

**Comment by bednar** [comment]
@webstersteele, thanks for using our client, We will take a look.
