### ISSUE TITLE
FluxResultMapper - support translating column name from some_col to someCol

### ISSUE THREAD

**Issue by uqix** [influxdata/influxdb-client-java#228]
__Proposal:__
support translating column name from `some_col` to `someCol` in `FluxResultMapper`.

__Current behavior:__
No translating, `@Column(name = "some_col")` is needed which is cumbersome.

__Desired behavior:__
Auto translating or configuration option provided.

__Alternatives considered:__
`@Column(name = "some_col")`.

__Use case:__
To follow our naming convention on both sides.

**Comment by bednar** [comment]
@uqix, thanks for the suggestion 👍 Is this something you might be willing to help with?

**Comment by uqix** [comment]
@bednar will do
