### ISSUE TITLE
Need help with dependency

### ISSUE THREAD

**Issue by hyeinkwon798** [influxdata/influxdb-client-java#232]
Hi im hyein 
Ima uni student in South Korea
Im trying to use java client to connect with rabbitmq and influxdb2.0
Im quite curious hiw to use this client
I have cloned the git to my computer which os is ubuntu 
Bit after all i don’t understand the next step
Do i have to change the pom.xml which is in the influxdb-client-directory? If it is, it says i have to write the version. What version do i have to write? The influxdb? The maven?
If you know could you tell me how i have to make this system move and if it gets ready how how could i compile my java code?? 
please needs some help!!p

Thank you for suggesting an idea to improve this client. 

* Please add a :+1: or comment on a similar existing feature request instead of opening a new one.
    * https://github.com/influxdata/influxdb-client-java/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+is%3Aclosed+sort%3Aupdated-desc+label%3A%22enhancement%22+

-->

__Proposal:__
Short summary of the feature.

__Current behavior:__
Describe what currently happens.

__Desired behavior:__
Describe what you want.

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by bednar** [comment]
Hi @hyeinkwon798,

thanks for using our client.

You can use our client as a dependency for your Maven or Gradle project:

- https://maven.apache.org/guides/getting-started/maven-in-five-minutes.html
- https://docs.gradle.org/current/userguide/getting_started.html

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
