### ISSUE TITLE
error using it

### ISSUE THREAD

**Issue by hyeinkwon798** [influxdata/influxdb-client-java#234]
<dependency>
  			<groupId>com.influxdb</groupId>
  			<artifactId>influxdb-client-java</artifactId>
 			<version>2.0.0</version>
		</dependency>

=> i have plused this dependency and then 'mvn clean install' in example directory

but there is an error 
[ERROR] Failed to execute goal com.mycila:license-maven-plugin:3.0:check (default) on project examples: Some files do not have the expected license header -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

what should i have to do?

**Comment by bednar** [comment]
Hi @hyeinkwon798,

some of your files doesn't have specified a license in header. You can use: `mvn license:format` for fix or run: `mvn clean install -Dlicense.skip=true` to skip this validation.

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
