### ISSUE TITLE
Get NumberFormatException for +Inf when I query a 'Histogram'

### ISSUE THREAD

**Issue by kaist997** [influxdata/influxdb-client-java#239]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Inject a query including Histogram with linearBins.
2. Get NumberFormatException : For input string: "+Inf"

__Expected behavior:__
Describe what you expected to happen.

Get a histogram without Exception.

__Actual behavior:__
Describe What actually happened.

Get NumberFormatException : For input string: "+Inf"

__Specifications:__
 - Client Version: 2.3.0
 - InfluxDB Version: 2.0.4 (git: 4e7a59bb9a)
 - JDK Version: 1.8.0_282
 - Platform: Ubuntu

**Comment by bednar** [comment]
Hi @kaist997,

thanks for using our client. We will take a look.

Regards

**Comment by bednar** [comment]
Testing data: [2021-06-25-08-50_influxdb_data.csv](https://github.com/influxdata/influxdb-client-java/files/6714118/2021-06-25-08-50_influxdb_data.csv)

**Comment by kaist997** [comment]
Thanks for the work!
