### ISSUE TITLE
Spring integration is using the `spring` namespace

### ISSUE THREAD

**Issue by snicoll** [influxdata/influxdb-client-java#243]
I've noticed this project bring spring integration. It's great to see some advanced configuration for users but that creates a  cycle between Spring Boot and this project as we've started to provide dependency management for it.

Please note that we require third party integration to not use our namespace, see [the documentation for more details](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.developing-auto-configuration.custom-starter.configuration-keys). Can you please rename the `spring.influxdb2` namespace? I suggest to use `influx`.

**Comment by bednar** [comment]
Hi @snicoll,

thanks for supports our client in the Spring. I will rename namespace to `influx` as you suggesting.

Regards
