### ISSUE TITLE
JAVA client can't get value

### ISSUE THREAD

**Issue by DomTeng** [influxdata/influxdb-client-java#245]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. install influxDB
2. JAVA write data
3. JAVA read data to POJO

__Expected behavior:__
the value POJO is right.

__Actual behavior:__
the value is null

__Specifications:__
 - Client Version: 3.0.0
 - InfluxDB Version: 2.0.7
 - JDK Version: 1.8.0_281
 - Platform: windows

other
`
@Measurement(name = "temperature")
public class Temperature {

    @Column(tag = true)
    public String location;

    @Column
    public Long volume;

    @Column
    public Long temp;

    @Column(timestamp = true)
    public Instant time;

}

    public void test05(){
        Temperature temperature = new Temperature();
        temperature.location = "south";
        temperature.volume = 62L;
        temperature.temp = 19L;
        temperature.time = Instant.now();
        InfluxClient.INSTANCE.write(temperature,"test");
    }

    public void test06(){
        InfluxDBClient influxDBClient = InfluxDBClientFactory.create("http://localhost:8086", "REsLiStwRiadaQs5VNt7aGcEM96qBxxKDRrWmkCaHEcfGi-c6pBqahTF9agC-bLjOE6xcKTHdrjet9ip862S-Q==".toCharArray(), "DIEHL", "test");
        QueryApi queryApi = influxDBClient.getQueryApi();

        String start = "2021-07-14T02:11:59.798Z";
        String stop = "2021-07-14T04:13:05.129Z";

        String template =
                " from(bucket:\"%s\") " +
                        " |> range(start: %s, stop: %s)" +
                        " |> filter(fn: (r) => " +
                        "    r._measurement == \"temperature\"" +
                        "  )";
        String flux = String.format(template,"test",start,stop);
        System.out.println(flux);
        List<Temperature> temperatures = queryApi.query(flux,"DIEHL",Temperature.class);
        System.out.println("共有："+temperatures.size());

        for (Temperature temperature : temperatures) {
            System.out.println(temperature.location+":"+temperature.volume+":"+temperature.time);//todo
        }
    }

`

**Comment by bednar** [comment]
Hi @DomTeng,

thanks for using our client. You have to use [pivot() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/pivot/) to transform data into tabular form. Something like:

```java
@Measurement(name = "temperature")
public class Temperature {

    @Column(tag = true)
    public String location;

    @Column
    public Long volume;

    @Column
    public Long temp;

    @Column(timestamp = true)
    public Instant time;
}
```

```java
@Test
void writeQuery()
{
    InfluxDBClient client = InfluxDBClientFactory.create("http://localhost:9999",
            "my-token".toCharArray(),
            "my-org",
            "my-bucket");
    Temperature temperature = new Temperature();
    temperature.location = "south";
    temperature.volume = 62L;
    temperature.temp = 19L;
    temperature.time = Instant.now();

    //
    // write
    //
    client.getWriteApiBlocking().writeMeasurement(WritePrecision.NS, temperature);

    //
    // query
    //
    String start = "2021-07-13T02:11:59.798Z";
    String stop = "2021-07-15T04:13:05.129Z";




    String template =
            " from(bucket:\"%s\") " +
                    " |> range(start: %s, stop: %s)" +
                    " |> filter(fn: (r) => " +
                    "    r._measurement == \"temperature\"" +
                    "  )" +
            " |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")";



    String flux = String.format(template, "my-bucket", start, stop);
    System.out.println(flux);
    List<Temperature> temperatures = client.getQueryApi().query(flux, Temperature.class);
    System.out.printf("Size：%d%n", temperatures.size());

    for (Temperature it : temperatures) {
        System.out.printf("%s : %d : %d : %s%n", it.location, it.volume, it.temp, it.time);
    }
}
```

Regards

**Comment by DomTeng** [comment]
@bednar thanks for your help.

but it is still null

- console log

`
Size：1
south : null : 19 : 2021-07-14T05:38:19Z
`

- UI console

#
![Screenshot_1](https://user-images.githubusercontent.com/20020743/125569699-c89fcf44-8856-43e6-867b-a0dde3b778c0.png)

the value of volume is null.

**Comment by bednar** [comment]
Can you share debug output from client? You can enable debug mode by:

```
InfluxDBClient client = InfluxDBClientFactory.create("http://localhost:9999",
        "my-token".toCharArray(),
        "my-org",
        "my-bucket");
client.setLogLevel(LogLevel.BODY);
```

**Comment by DomTeng** [comment]
Hi, @bednar 

it's my mistake, i had added one more filter. now it can work well.

thanks very much
