### ISSUE TITLE
Memory consumption when retrieving huge result data

### ISSUE THREAD

**Issue by fenjen** [influxdata/influxdb-client-java#253]
When querying the InfluxDB for large results, the okio client seems to hold the entire response in local byte arrays. 

I'm querying data with `com.influxdb.client.QueryApi.query(String, BiConsumer<Cancellable, FluxRecord>, Consumer<? super Throwable>, Runnable)`. The result data is huge, but the Consumer aggregates it efficiently. Yet my JVM stops frequently because the okio client seems to hold references to the entire response. The heap dump analyzer shows variables that contain the whole original CSV data.

Also I can't cancel the request until the whole response was read into memory, because the `BiConsumer` is given result data too late.

See attached image for details.
![okio-heap-consumption](https://user-images.githubusercontent.com/2162388/128209874-e1dd7100-770e-4ab9-9e44-ab63130826e5.png)

__Specifications:__
 - Client Version: 2.2.0
 - InfluxDB Version: 2.0.4
 - JDK Version: 11
 - Platform: all

**Comment by bednar** [comment]
@fenjen thanks for using our client, we will take a look.

**Comment by bednar** [comment]
@fenjen I have prepared a fixed version within #254. Development version of the client will be available after #254 acceptance, stable version in regular release cycle.

**Comment by fenjen** [comment]
@bednar That was fast! I've tested your change. The process doesn't seem to allocate noteworthy amounts of RAM any more when receiving huge result data! 👍 Thanks!

**Comment by bednar** [comment]
@fenjen thanks for testing 🤝
