### ISSUE TITLE
getUsersApi().me() returns UnauthorizedException for valid token

### ISSUE THREAD

**Issue by vanduc2514** [influxdata/influxdb-client-java#261]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

```java
// Create a new InfluxDBClient with 
InfluxDBClient client = InfluxDBClientFactory.create(
                    "my-url",
                    "generated-token-from-influx".toCharArray(),
                    "my-organization",
                    "my-bucket-name"
); 

// Then call the method
User user = client.getUsersApi().me()

```

__Expected behavior:__
Method return `User`.

__Actual behavior:__
Method throw `UnauthorizedException` with status code 401

__Specifications:__
 - Client Version: 3.2.0
 - InfluxDB Version: 2.0
 - JDK Version: openJDK 11
 - Platform: Docker Container

**Comment by bednar** [comment]
Hi @vanduc2514,

thanks for using our client. 

You have to use the token with `All Access Scope` then the response will be success. It might be an issue at InfluxDB 2 Cloud... I will reach a Cloud team.

Regards

**Comment by vanduc2514** [comment]
Thank you for your response. I granted all-access scope (read/write) for the token and the API returned with the correct Response. However, it's not a practical solution since some of the buckets only have read access, because of security. Currently, I don't know any way to circumvent this situation.

**Comment by bednar** [comment]
As a solution you can create the token with scope to read the bucket and users via `authorization` API:

```bash
URL='http://localhost:8086'
TOKEN='my-token'
USER="my-user"
USER_ID='081d0c6e8b779000'
ORG_ID='739889093fe18692'
BUCKET_ID='0f36194026677344'

curl --location --request POST "$URL/api/v2/authorizations" \
--header 'Content-Type: application/json' \
--header "Authorization: Token $TOKEN" \
--data-raw "{
    \"description\": \"Read only bucket and users\",
    \"orgID\": \"$ORG_ID\",
    \"permissions\": [
        {
            \"action\": \"read\",
            \"resource\": {
                \"orgID\": \"$ORG_ID\",
                \"id\": \"$BUCKET_ID\",
                \"type\": \"buckets\"
            }
        },
        {
            \"action\": \"read\",
            \"resource\": {
                \"type\": \"users\",
                \"id\": \"$USER_ID\",
                \"name\": \"$USER\"
            }
        }
    ],
    \"userID\": \"081d0c6e8b779000\"
}"
```

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
