### ISSUE TITLE
How to set timeout QueryAPI?

### ISSUE THREAD

**Issue by duongxinh2003** [influxdata/influxdb-client-java#262]
I used QueryAPI to get data following example:
`QueryApi queryApi = influxDBClient.getQueryApi();
List<FluxTable> tables = queryApi.query(flux);`
And after 10 seconds I got exception
`Exception in thread "main" com.influxdb.exceptions.InfluxException: Read timed out`
I don't want to timeout and how to set it? Thanks!

**Comment by bednar** [comment]
Hi @duongxinh2003 ,

You can customize HTTP connection timeouts via:

```java
OkHttpClient.Builder builder = new OkHttpClient.Builder()
    .readTimeout(30, TimeUnit.SECONDS)
    .writeTimeout(30, TimeUnit.SECONDS)
    .connectTimeout(30, TimeUnit.SECONDS);

InfluxDBClientOptions options = InfluxDBClientOptions.builder()
    .url("http://localhost:8086")
    .authenticateToken("my-token".toCharArray())
    .okHttpClient(builder)
    .build();

InfluxDBClient client = InfluxDBClientFactory.create(options);
```

Regards

**Comment by duongxinh2003** [comment]
Hi @bednar ,
I tried it and it seem work well.
Thanks for supporting me to complete this code!
