### ISSUE TITLE
Javadoc links are broken

### ISSUE THREAD

**Issue by climategadgets** [influxdata/influxdb-client-java#264]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Visit a project page, for example https://github.com/influxdata/influxdb-client-java/tree/master/client-reactive
2. Click on a doc link (examples: https://influxdata.github.io/influxdb-client-java/influxdb-client-reactive/apidocs/org/influxdata/client/reactive/QueryReactiveApi.html, https://influxdata.github.io/influxdb-client-java/influxdb-client-reactive/apidocs/org/influxdata/client/reactive/WriteReactiveApi.html)

__Expected behavior:__
Documentation page should appear.

__Actual behavior:__
404 error is encountered

**Comment by bednar** [comment]
Hi @climategadgets,

thanks for report broken links. 

I've push fixed READMEs in https://github.com/influxdata/influxdb-client-java/commit/3d771d497dc45322be8b94f70e8b49f6dab95dac

Regards
