### ISSUE TITLE
FluxResultMapper toPojo should map _fields

### ISSUE THREAD

**Issue by derXear** [influxdata/influxdb-client-java#265]
__Proposal:__
Can we extend the FluxResultMapper::toPojo method to also map values of `_field` into the given POJO?

__Current behavior:__
In the current implementation of the method there is this part:
```
if (recordValues.containsKey(columnName)) {
  col = columnName;
} else if (recordValues.containsKey("_" + columnName)) {
  col = "_" + columnName;
} else {
  String columnNameInSnakeCase = camelCaseToSnakeCase(columnName);
  if (recordValues.containsKey(columnNameInSnakeCase)) {
    col = columnNameInSnakeCase;
  }
}
```
This is not taking into consideration, that the POJO members might be part of the `_field`.

__Desired behavior:__
I would love to have something like this added:
```
else if (recordValues.containsKey("_field") && recordValues.get("_field").equals(columnName)) {
  col = "_value";
} 
```

__Alternatives considered:__
Or maybe is there already some other approach to getting my desired result?

__Use cases:__
You can find the more described Problem with examples on [Stackoverflow](https://stackoverflow.com/questions/69128316/influxdb-fluxresultmapper-not-mapping-by-fields)

Have a nice day! :)

**Comment by bednar** [comment]
Hi @derXear,

thanks for using our client. 

How looks like your query? Do you use [pivot() function](https://docs.influxdata.com/influxdb/v2.0/reference/flux/stdlib/built-in/transformations/pivot/)? The `pivot` switch the result of query into tabular format and `FluxResultMapper` correctly map result into POJOs.

Regards

**Comment by derXear** [comment]
Hi @bednar,

seems to be obvious that I'm pretty new to InfluxDB in general :sweat_smile: 
Thats absolutely what I was looking for. 

Thank you, and keep up the good work!
