### ISSUE TITLE
add query by name for buckets，tasks and orgs api

### ISSUE THREAD

**Issue by lonelyleaf** [influxdata/influxdb-client-java#277]
__Proposal:__
Add query param for taskApi and orgApi for query by name。

__Use case:__
In my case，I need add bucket by code in runtime，but I need find all task first，and then filter them by name。Influxdb's rest api have this feature but why you not open it in java client?

**Comment by bednar** [comment]
Hi @lonelyleaf,

The `TaskApi` and `OrgApi` do not copy InfluxDB 2 HTTP API at 100% level, but you are able to directly use `OrganizationsService` and `TasksService`.

Something like will works:

```java
package example;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.domain.Organization;
import com.influxdb.client.domain.Task;
import com.influxdb.client.service.OrganizationsService;
import com.influxdb.client.service.TasksService;

public class PlatformExample {

    public static void main(final String[] args) throws Exception {

        String url = "http://localhost:8086";
        String token = "my-token";

        String orgName = "my-org";
        String taskName = "my-task";

        try (InfluxDBClient client = InfluxDBClientFactory.create(url, token.toCharArray()))
        {
            OrganizationsService organizations = client.getService(OrganizationsService.class);
            Organization org = organizations.getOrgs(null, null, null, null, orgName, null, null)
                    .execute()
                    .body()
                    .getOrgs()
                    .get(0);

            System.out.println("org = " + org);

            TasksService tasks = client.getService(TasksService.class);
            Task task = tasks.getTasks(null, taskName, null, null, null, null, null, null)
                    .execute()
                    .body()
                    .getTasks()
                    .get(0);

            System.out.println("task = " + task);
        }
    }
}
```

Regards

**Comment by lonelyleaf** [comment]
@bednar thank you，your replay is very helpful.But why not add one method with param like

```java
findTask(TaskQuery taskQuery)

public class TaskQuery {
    String after;
    String name;
    String org;
    String orgId;
    String String;
    String status;
    String type;
    String user;
}

```

no need to hide so many information from rest api,but add so many method with different params

**Comment by bednar** [comment]
> @bednar thank you，your replay is very helpful.But why not add one method with param like
> 
> ```java
> findTask(TaskQuery taskQuery)
> 
> public class TaskQuery {
>     String after;
>     String name;
>     String org;
>     String orgId;
>     String String;
>     String status;
>     String type;
>     String user;
> }
> ```
> 
> no need to hide so many information from rest api,but add so many method with different params

@lonelyleaf thanks for the suggestion 👍. Is this something you might be willing to help with?

**Comment by lonelyleaf** [comment]
@bednar 
can this pull request be helped?
https://github.com/influxdata/influxdb-client-java/pull/278

**Comment by bednar** [comment]
@lonelyleaf, of course. It is awesome improvement 👍.

I will review your PR later today.

Thanks for PR 👍
