### ISSUE TITLE
Client failing to save when Tag value is null

### ISSUE THREAD

**Issue by eduelias** [influxdata/influxdb-client-java#282]
Looking at "master"'s code [here](https://github.com/influxdata/influxdb-client-java/blob/f2ef610eda2aa39a14c58199f025715210829c3d/client/src/main/java/com/influxdb/client/write/Point.java#L348) you can see:
``` 
String value = tag.getValue()
``` 

And, two lines down, we check:
```
if (key.isEmpty() || value.isEmpty())
```

But if value is null, "isEmpty" will throw an unwanted "NullPointException". Instead, in this place, we should check value != null and then value.isEmpty(). 

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. append a tag with null value

__Expected behavior:__
Ignore the tag

__Actual behavior:__
Throws error

__Specifications:__
 - Client Version: current master
 - InfluxDB Version: 2.1
 - JDK Version: 11
 - Platform: Windows/MacOS

**Comment by bednar** [comment]
Hi @eduelias,

thanks for using our client and report this bug.

I have prepared a fixed version within #283. Development version of the client will be available after #283 acceptance, stable version in regular release cycle.

Regards
