### ISSUE TITLE
The latest Java version failed to insert data

### ISSUE THREAD

**Issue by ygao0928** [influxdata/influxdb-client-java#288]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

When Java is using the latest Influx3.1.0, insert data and set time. The operation succeeds only when 'instant.now ()' is used, and the user-defined time cannot be used

**Comment by bednar** [comment]
Hi @ygao0928,

thanks for using our client.

Can you share an exception that is thrown by client or debug information? You can enable debug by: 

```
client.setLogLevel(LogLevel.BODY);
```

Did you set correct time in UI?

![image](https://user-images.githubusercontent.com/455137/145767150-7d6555ae-4811-44d3-b6f8-856aca9eed4b.png)

Regards

**Comment by ygao0928** [comment]
### Thanks for your answer，
### Now，Time data can be inserted, But the  valus are errors;
## The current data is a 10-bit timestamp, but converting to 13 bits is problematic
![image](https://user-images.githubusercontent.com/31363729/145827877-651329ad-20c4-453d-b623-9abf981af1cc.png)

BUT
![image](https://user-images.githubusercontent.com/31363729/145827979-eb402b92-4d85-43b9-a9f0-2c5b57e3cd82.png)

**Comment by bednar** [comment]
It looks like that the UI uses aggregatedWindow function. Try to switch to `Script Editor` and edit your query.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
