### ISSUE TITLE
apiClient.getDeleteApi().delete timeout

### ISSUE THREAD

**Issue by hinst** [influxdata/influxdb-client-java#289]
Good day

I am getting HTTP timeout error whilst using InfluxDB but only for the `delete` operation. Reads and writes seem to be fine. Can someone please tell me what timeout is used for the `delete` operation in `influxdb-client-java`? Is it the same timeout that can be specified in `OkHttpClient.Builder().readTimeout().writeTimeout()` ?   Thanks

**Comment by bednar** [comment]
Hi @hinst,

thanks for using our client.

> Is it the same timeout that can be specified in `OkHttpClient.Builder().readTimeout().writeTimeout()` ? Thanks

Yes

Regards

**Comment by hinst** [comment]
Ok thanks for the quick response
