### ISSUE TITLE
proposal: Update Swagger dependencies to v3 (OpenApi generator v5)

### ISSUE THREAD

**Issue by aDramaQueen** [influxdata/influxdb-client-java#295]
Hi,
not very urgent proposal, but would be a "nice to have".

__Proposal:__
Updated internal dependencies from Swagger2 `io.swagger:swagger-annotations:1.6.1` to OpenAPI (a.k.a Swagger3) `io.swagger.core.v3:swagger-annotations:2.1.12`

__Current behavior:__
No OpenAPI integration.

__Desired behavior:__
OpenAPI integration.

__Use case:__
Writing an API with Influx.

Thank you

**Comment by bednar** [comment]
Hi @aDramaQueen,

thanks for using our client.

This is breaking change which we are able to do in future major release. I don't have ETA, but we will take a look.

Regards
