### ISSUE TITLE
Spring: Application run failed

### ISSUE THREAD

**Issue by droni1234** [influxdata/influxdb-client-java#296]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Try to use com.influxdb:influxdb-spring:4.0.0 without Spring boot Actuator
2. Autowire InfluxDBClient and try to make a call

__Expected behavior:__
Spring boots up.
And query works as expected.

__Actual behavior:__
Spring fails to boot up
Describe What actually happened.

```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-01-13 14:59:03.153 ERROR 4480 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [de.thkoeln.syp.team17.backend.BackendApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/boot/actuate/autoconfigure/health/CompositeHealthContributorConfiguration.class] cannot be opened because it does not exist
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser.access$800(ConfigurationClassParser.java:111) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:812) ~[spring-context-5.3.13.jar:5.3.13]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.1.jar:2.6.1]
	at de.thkoeln.syp.team17.backend.BackendApplication.main(BackendApplication.java:14) ~[main/:na]
Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/actuate/autoconfigure/health/CompositeHealthContributorConfiguration.class] cannot be opened because it does not exist
	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[spring-boot-2.6.1.jar:2.6.1]
	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[spring-core-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:696) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:1010) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:341) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.3.13.jar:5.3.13]
	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:600) ~[spring-context-5.3.13.jar:5.3.13]
	... 19 common frames omitted


Process finished with exit code 1
```

__Specifications:__
 - Client Version: 4.0.0
 - InfluxDB Version: 2.X.X
 - JDK Version: openjdk 11
 - Platform: Windows 8.1/ MacOS 12.1

**Comment by bednar** [comment]
Hi @droni1234,

thanks for using our client.





> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2022-01-13 14:59:03.153 ERROR 4480 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 
> org.springframework.beans.factory.BeanDefinitionStoreException: Failed to process import candidates for configuration class [de.thkoeln.syp.team17.backend.BackendApplication]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/boot/actuate/autoconfigure/health/CompositeHealthContributorConfiguration.class] cannot be opened because it does not exist
> 	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:610) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser.access$800(ConfigurationClassParser.java:111) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.lambda$processGroupImports$1(ConfigurationClassParser.java:812) ~[spring-context-5.3.13.jar:5.3.13]
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540) ~[na:na]
> 	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorGroupingHandler.processGroupImports(ConfigurationClassParser.java:809) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser$DeferredImportSelectorHandler.process(ConfigurationClassParser.java:780) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:193) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:412) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1290) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at de.thkoeln.syp.team17.backend.BackendApplication.main(BackendApplication.java:14) ~[main/:na]
> Caused by: java.io.FileNotFoundException: class path resource [org/springframework/boot/actuate/autoconfigure/health/CompositeHealthContributorConfiguration.class] cannot be opened because it does not exist
> 	at org.springframework.core.io.ClassPathResource.getInputStream(ClassPathResource.java:199) ~[spring-core-5.3.13.jar:5.3.13]
> 	at org.springframework.core.type.classreading.SimpleMetadataReader.getClassReader(SimpleMetadataReader.java:55) ~[spring-core-5.3.13.jar:5.3.13]
> 	at org.springframework.core.type.classreading.SimpleMetadataReader.<init>(SimpleMetadataReader.java:49) ~[spring-core-5.3.13.jar:5.3.13]
> 	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:103) ~[spring-core-5.3.13.jar:5.3.13]
> 	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.createMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:86) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.boot.type.classreading.ConcurrentReferenceCachingMetadataReaderFactory.getMetadataReader(ConcurrentReferenceCachingMetadataReaderFactory.java:73) ~[spring-boot-2.6.1.jar:2.6.1]
> 	at org.springframework.core.type.classreading.SimpleMetadataReaderFactory.getMetadataReader(SimpleMetadataReaderFactory.java:81) ~[spring-core-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser.asSourceClass(ConfigurationClassParser.java:696) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser$SourceClass.getSuperClass(ConfigurationClassParser.java:1010) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:341) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.3.13.jar:5.3.13]
> 	at org.springframework.context.annotation.ConfigurationClassParser.processImports(ConfigurationClassParser.java:600) ~[spring-context-5.3.13.jar:5.3.13]
> 	... 19 common frames omitted
> 
> 
> Process finished with exit code 1

The client actually depends on `spring-boot-actuator`... I will update `README.md` to clarify how to use `influxdb-spring` without `spring-boot-actuator`.



> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> An attempt was made to call a method that does not exist. The attempt was made from the following location:
> 
>     com.influxdb.client.internal.AuthenticateInterceptor.initToken(AuthenticateInterceptor.java:122)
> 
> The following method did not exist:
> 
>     'okhttp3.RequestBody okhttp3.RequestBody.create(java.lang.String, okhttp3.MediaType)'
> 
> The calling method's class, com.influxdb.client.internal.AuthenticateInterceptor, was loaded from the following location:
> 
>     jar:file:/C:/Users/phili/.gradle/caches/modules-2/files-2.1/com.influxdb/influxdb-client-java/4.0.0/c9b3a066f15c0bd8799936c623a8d096c86c64fd/influxdb-client-java-4.0.0.jar!/com/influxdb/client/internal/AuthenticateInterceptor.class
> 
> The called method's class, okhttp3.RequestBody, is available from the following locations:
> 
>     jar:file:/C:/Users/phili/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.14.9/3e6d101343c7ea687cd593e4990f73b25c878383/okhttp-3.14.9.jar!/okhttp3/RequestBody.class
> 
> The called method's class hierarchy was loaded from the following locations:
> 
>     okhttp3.RequestBody: file:/C:/Users/phili/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.14.9/3e6d101343c7ea687cd593e4990f73b25c878383/okhttp-3.14.9.jar
> 
> 
> Action:
> 
> Correct the classpath of your application so that it contains compatible versions of the classes com.influxdb.client.internal.AuthenticateInterceptor and okhttp3.RequestBody
> 
> 
> Process finished with exit code 1

It looks like same problem as is mentioned in https://github.com/influxdata/influxdb-client-java/issues/290

Regards.

**Comment by rts-gordon** [comment]
Hi @bednar 
  I use influxdb-spring latest version 6.7.0 in my project, and　there is the same issue: 
```
Failed to process import candidates for configuration class [com.lifebyte.hubx.ohlc.Application]; nested exception is java.io.FileNotFoundException: class path resource [org/springframework/boot/actuate/autoconfigure/health/CompositeHealthContributorConfiguration.class] cannot be opened because it does not exist
```

So I had to include spring component "actuator" in pom.xml to solve the issue, but I think it is not a reasonable way:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-actuator-autoconfigure</artifactId>
        </dependency>
        <dependency>
            <groupId>com.influxdb</groupId>
            <artifactId>influxdb-spring</artifactId>
            <version>${influxdb-client-version}</version>
        </dependency>
```

There is nothing about "how to use influxdb-spring without spring-boot-actuator." in the README.md, can you please explain how to do this?   Import "spring-boot-actuator-autoconfigure" in pom.xml, or another better way? 

Thank you very much.

**Comment by bednar** [comment]
Hi @rts-gordon,

which version of the `spring` do you use?

Regards

**Comment by rts-gordon** [comment]
Hi @bednar 
  It is 2.6.4 of spring boot version,  6.7.0 of influxdb-spring.

 Regards

**Comment by rts-gordon** [comment]
Hi @bednar 
  May I to know any progress about this?

Regards

**Comment by bednar** [comment]
It looks like problem without your classpath not the client. The `CompositeHealthContributorConfiguration` is part of `spring-boot-actuator-autoconfigure`. Can you list your dependency tree by `mvn dependency:tree`?

**Comment by bednar** [comment]
@rts-gordon It looks like problem without your classpath not the client. The `CompositeHealthContributorConfiguration` is part of `spring-boot-actuator-autoconfigure`. Can you list your dependency tree by `mvn dependency:tree`?

**Comment by rts-gordon** [comment]
Sure, my program dependency as follows:
```
mvn dependency:tree
[INFO] Scanning for projects...
[INFO] 
[INFO] 
[INFO] --- maven-dependency-plugin:3.2.0:tree (default-cli) @ hubx-core-ohlc ---
[INFO] com.company.hubx:hubx-core-ohlc:jar:0.4.0-SNAPSHOT
[INFO] +- com.company.hubx:hubx-server-common:jar:0.4.0-SNAPSHOT:compile
[INFO] |  +- org.projectlombok:lombok:jar:1.18.22:compile
[INFO] |  +- com.company-common-avro:jar:0.4.0-SNAPSHOT:compile
[INFO] |  +- com.lmax:disruptor:jar:3.4.4:compile
[INFO] |  +- org.springframework.security:spring-security-messaging:jar:5.6.2:compile
[INFO] |  |  +- org.springframework.security:spring-security-core:jar:5.6.2:compile
[INFO] |  |  |  \- org.springframework.security:spring-security-crypto:jar:5.6.2:compile
[INFO] |  |  \- org.springframework:spring-messaging:jar:5.3.16:compile
[INFO] |  \- com.h2database:h2:jar:1.4.200:running
[INFO] +- org.springframework.boot:spring-boot-starter-data-redis:jar:2.6.4:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.6.4:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.6.4:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.10:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.10:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.1:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.1:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.29:compile
[INFO] |  +- org.springframework.data:spring-data-redis:jar:2.6.2:compile
[INFO] |  |  +- org.springframework.data:spring-data-keyvalue:jar:2.6.2:compile
[INFO] |  |  |  \- org.springframework.data:spring-data-commons:jar:2.6.2:compile
[INFO] |  |  +- org.springframework:spring-tx:jar:5.3.16:compile
[INFO] |  |  +- org.springframework:spring-oxm:jar:5.3.16:compile
[INFO] |  |  \- org.springframework:spring-context-support:jar:5.3.16:compile
[INFO] |  \- io.lettuce:lettuce-core:jar:6.1.6.RELEASE:compile
[INFO] |     +- io.netty:netty-common:jar:4.1.74.Final:compile
[INFO] |     +- io.netty:netty-handler:jar:4.1.74.Final:compile
[INFO] |     |  +- io.netty:netty-resolver:jar:4.1.74.Final:compile
[INFO] |     |  +- io.netty:netty-buffer:jar:4.1.74.Final:compile
[INFO] |     |  +- io.netty:netty-codec:jar:4.1.74.Final:compile
[INFO] |     |  \- io.netty:netty-tcnative-classes:jar:2.0.48.Final:compile
[INFO] |     +- io.netty:netty-transport:jar:4.1.74.Final:compile
[INFO] |     \- io.projectreactor:reactor-core:jar:3.4.15:compile
[INFO] |        \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
[INFO] +- com.alibaba:fastjson:jar:1.2.80:compile
[INFO] +- org.springframework:spring-context:jar:5.3.16:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.3.16:compile
[INFO] |  +- org.springframework:spring-beans:jar:5.3.16:compile
[INFO] |  +- org.springframework:spring-core:jar:5.3.16:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.16:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.3.16:compile
[INFO] +- org.springframework.boot:spring-boot-autoconfigure:jar:2.6.4:compile
[INFO] |  \- org.springframework.boot:spring-boot:jar:2.6.4:compile
[INFO] +- com.company.hubx:common-kafka:jar:1.8.0-SNAPSHOT:compile
[INFO] |  +- org.apache.kafka:kafka-clients:jar:3.0.0:compile
[INFO] |  |  +- com.github.luben:zstd-jni:jar:1.5.0-2:runtime
[INFO] |  |  +- org.lz4:lz4-java:jar:1.7.1:runtime
[INFO] |  |  \- org.xerial.snappy:snappy-java:jar:1.1.8.1:runtime
[INFO] |  +- net.sf.trove4j:trove4j:jar:3.0.3:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.13.1:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.1:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.1:compile
[INFO] |  +- org.apache.avro:avro:jar:1.11.0:compile
[INFO] |  |  \- org.apache.commons:commons-compress:jar:1.21:compile
[INFO] |  \- org.springframework.kafka:spring-kafka:jar:2.8.3:compile
[INFO] |     \- org.springframework.retry:spring-retry:jar:1.3.1:compile
[INFO] +- com.vladkrava:avro-converter:jar:1.0.1:compile
[INFO] |  +- org.json:json:jar:20180813:compile
[INFO] |  \- org.springframework:spring-web:jar:5.3.16:compile
[INFO] +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.6.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.6.4:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.6.4:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.6.0:test
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.8:test
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.8:test
[INFO] |  |        \- org.ow2.asm:asm:jar:9.1:test
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:test
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:test
[INFO] |  +- org.assertj:assertj-core:jar:3.21.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.0.0:test
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.11.22:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.11.22:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.0.0:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.0:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-test:jar:5.3.16:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.8.4:test
[INFO] +- org.apache.commons:commons-pool2:jar:2.11.1:compile
[INFO] +- tech.tablesaw:tablesaw-core:jar:0.43.1:compile
[INFO] |  +- com.google.guava:guava:jar:30.0-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:3.5.0:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
[INFO] |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  +- it.unimi.dsi:fastutil:jar:8.3.0:compile
[INFO] |  +- org.roaringbitmap:RoaringBitmap:jar:0.9.25:compile
[INFO] |  |  \- org.roaringbitmap:shims:jar:0.9.25:runtime
[INFO] |  +- com.univocity:univocity-parsers:jar:2.8.4:compile
[INFO] |  +- com.ibm.icu:icu4j:jar:65.1:compile
[INFO] |  +- io.github.classgraph:classgraph:jar:4.8.60:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.6.4:compile
[INFO] |  \- org.springframework.boot:spring-boot-actuator:jar:2.6.4:compile
[INFO] \- com.influxdb:influxdb-spring:jar:6.7.0:compile
[INFO]    +- com.influxdb:influxdb-client-java:jar:6.7.0:compile
[INFO]    |  +- com.influxdb:influxdb-client-core:jar:6.7.0:compile
[INFO]    |  |  +- com.influxdb:influxdb-client-utils:jar:6.7.0:compile
[INFO]    |  |  +- com.squareup.okio:okio:jar:3.2.0:compile
[INFO]    |  |  |  \- com.squareup.okio:okio-jvm:jar:3.2.0:compile
[INFO]    |  |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.10:compile
[INFO]    |  |  |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.6.10:compile
[INFO]    |  |  +- com.squareup.okhttp3:okhttp:jar:4.10.0:compile
[INFO]    |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.10:compile
[INFO]    |  |  |     +- org.jetbrains:annotations:jar:13.0:compile
[INFO]    |  |  |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.6.10:compile
[INFO]    |  |  +- com.squareup.retrofit2:retrofit:jar:2.9.0:compile
[INFO]    |  |  +- com.squareup.okhttp3:logging-interceptor:jar:4.10.0:compile
[INFO]    |  |  +- org.apache.commons:commons-csv:jar:1.9.0:compile
[INFO]    |  |  \- com.google.code.gson:gson:jar:2.8.9:compile
[INFO]    |  +- io.reactivex.rxjava3:rxjava:jar:3.1.5:compile
[INFO]    |  +- com.squareup.retrofit2:adapter-rxjava3:jar:2.9.0:compile
[INFO]    |  +- com.squareup.retrofit2:converter-scalars:jar:2.9.0:compile
[INFO]    |  \- com.squareup.retrofit2:converter-gson:jar:2.9.0:compile
[INFO]    \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```

**Comment by bednar** [comment]
@rts-gordon The client `6.7.0` depends on the spring-boot `2.7.5`. Try to update your dependencies to this version.

**Comment by rts-gordon** [comment]
OK, I will try, thanks for your help.

**Comment by rts-gordon** [comment]
@bednar 
I upgraded spring-boot to 2.7.5, but it is still need the dependency "spring-boot-actuator-autoconfigure" in pom.xml, otherwise there are the same errors.

If the dependency "spring-boot-actuator-autoconfigure" in pom.xml is necessary, I think it would be better to write in README file or develop document.

**Comment by flortsch** [comment]
Faced the same issue. README does not mention the requirement for spring-boot-actuator-autoconfigure.

**Comment by bednar** [comment]
@flortsch, I will update README during migration to Spring Boot v3

**Comment by tex1988** [comment]
So what is the way to use influxdb-spring without actuator in classpath?
