### ISSUE TITLE
One connection, different tasks

### ISSUE THREAD

**Issue by wise-coders** [influxdata/influxdb-client-java#299]
I need to create a single connection and be able to list the buckets, tags, fields, etc, and also execute Flux queries. 
How is this possible? 
Right now I see there is an InfluxDBClient and FluxConnection, each separate.
Can you please help me with some code to list the structure of a database?

**Comment by bednar** [comment]
Hi @wise-coders,

thanks for using our client

> I need to create a single connection and be able to list the buckets, tags, fields, etc, and also execute Flux queries.
> How is this possible?

Just initialise the client with proper token.


```java
package example;

import java.util.function.Consumer;

import com.influxdb.client.BucketsApi;
import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.QueryApi;
import com.influxdb.client.domain.Bucket;

public class ConnectionExample {

    private static final char[] token = "my-token".toCharArray();
    private static final String org = "my-org";
    private static final String bucket = "my-bucket";

    public static void main(final String[] args) {

        try (InfluxDBClient client = InfluxDBClientFactory.create("http://localhost:8086", token, org, bucket)) {

            //
            // Bucket API
            //
            BucketsApi bucketsApi = client.getBucketsApi();
            bucketsApi.findBuckets().forEach(new Consumer<Bucket>() {
                @Override
                public void accept(final Bucket bucket) {
                    System.out.println("bucket = " + bucket);
                }
            });

            //
            // Query API
            //
            QueryApi queryApi = client.getQueryApi();
            
            ...
        }
    }
}
```

> Right now I see there is an InfluxDBClient and FluxConnection, each separate.
> Can you please help me with some code to list the structure of a database?

Try to use functions from Flux's `schema` package - https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/

Regards

**Comment by wise-coders** [comment]
Thank you for your reply. 
If I want to run both, Flex and SELECT queries, how can I do this? 
I tried using client.getQueryApi().query( queryText ) and works only with Flux.

**Comment by bednar** [comment]
The client doesn't suport InfluxQL. If you want to use the InfluxQL you have to use old one - https://github.com/influxdata/influxdb-java

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
