### ISSUE TITLE
Basic authentication expires after a while

### ISSUE THREAD

**Issue by gungorerhan** [influxdata/influxdb-client-java#308]
When I authenticate with basic authentication, it seems to be working for a while (a few hours).
I authenticate using the code below:
```
InfluxDBClientFactory.create(InfluxDBClientOptions.builder()
                .url(dbUrl)
                .org(ORGANIZATION)
                .authenticate(dbUser, dbPassword.toCharArray())
                .build());
```
After a few hours, I get "unauthorized access" error on any query. When I restart the container, everything works fine again.

Not: Authentication with token seems to be working expected.

__Steps to reproduce:__
1. Authenticate with basic authentication
2. Wait a few hours
3. See unauthorized error message

__Expected behavior:__
Authentication should not expire.

__Actual behavior:__
Authentication expires.

__Specifications:__
 - Client Version: 4.1.0
 - InfluxDB Version: 2.1.1
 - JDK Version: 1.8.0_292

**Comment by bednar** [comment]
Hi @gungorerhan,

thanks for using our client.

The username/password auth is based on [HTTP "Basic" authentication](http://bit.ly/http-basic-auth). The authorization expires when the [time-to-live (TTL) ](http://bit.ly/session-length) (default 60 minutes) is reached and client produces `com.influxdb.exceptions.UnauthorizedException`.

For long time connection use the `token` authentication.

For more info see:
- https://influxdata.github.io/influxdb-client-java/influxdb-client-java/apidocs/com/influxdb/client/InfluxDBClientOptions.Builder.html#authenticate-java.lang.String-char:A-
- https://docs.influxdata.com/influxdb/v2.0/reference/config-options/#session-length

Regards

**Comment by gungorerhan** [comment]
Thanks for the quick reply.
We just upgraded from influxdb 1.8 to 2.1. And I thought this was a bug but looks like there is no way to have non-expiring sessions (via basic auth) in influxdb 2.+ versions.

Due to the structure of our project, it is not feasible to have hardcoded tokens. If anyone has such a use case, here is a workaround:

```
        // login via basic auth 
        InfluxDBClient  influxDBClient = InfluxDBClientFactory.create(InfluxDBClientOptions.builder()
                .url(url)
                .org(org)
                .authenticate(username, password.toCharArray())
                .build());

        // get token from authorizations api
        String token = influxDBClient.getAuthorizationsApi()
                .findAuthorizationsByUserName(username)
                .stream()
                .findFirst()
                .get()
                .getToken();

        // login via token
        influxDBClient = InfluxDBClientFactory.create(dbUrl, authorization.getToken().toCharArray(), ORGANIZATION);
```

**Comment by sranka** [comment]
@gungorerhan FYI: The authorizations API of InfluxDB Cloud no longer returns tokens of created authorizations (https://docs.influxdata.com/influxdb/cloud/security/tokens/view-tokens/). InfluxDB OSS still returns the tokens, but the situation may change with new OSS versions to follow the cloud version.
