### ISSUE TITLE
how to use truncateTimeColumn or date.truncate?

### ISSUE THREAD

**Issue by sunnights** [influxdata/influxdb-client-java#309]
I can't find the truncateTimeColumn function in flux-dsl,
or is there anyway to use package "date"?
It's important to me.

**Comment by bednar** [comment]
Hi @sunnights,

thanks for using our client.

> I can't find the truncateTimeColumn function in flux-dsl,
or is there anyway to use package "date"?

Currently not, but you can create your own DSL function. Use the following code:

```java
public static class TruncateTimeColumn extends AbstractParametrizedFlux {

    public TruncateTimeColumn(@Nonnull final Flux source) {
        super(source);
    }

    @Nonnull
    @Override
    protected String operatorName() {
        return "truncateTimeColumn";
    }

    /**
     * @param unit The unit of time to truncate to.
     * @return this
     */
    @Nonnull
    public TruncateTimeColumn withUnit(@Nonnull final String unit) {

        Arguments.checkDuration(unit, "Unit");

        withPropertyValue("unit", unit);

        return this;
    }
}
```

```java
Flux flux = Flux
        .from("telegraf")
        .function(TruncateTimeColumn.class)
        .withUnit("1s");

System.out.println(flux);
```

Output:

```console
from(bucket:"telegraf")
	|> truncateTimeColumn(unit:1s)
```

Regards

**Comment by sunnights** [comment]
Thanks, it works for me!
I think you should update the [readme doc](https://github.com/influxdata/influxdb-client-java/tree/master/flux-dsl#custom-operator)
replace the `operator`  with `function`.

BTW, flux-dsl doesn't support set TimeZone, is there any plan to support it?

**Comment by bednar** [comment]
> Thanks, it works for me! I think you should update the [readme doc](https://github.com/influxdata/influxdb-client-java/tree/master/flux-dsl#custom-operator) replace the `operator` with `function`.

Good catch 👍, I will update the `README.md`.

> BTW, flux-dsl doesn't support set TimeZone, is there any plan to support it?

Currently not, Is this something you might be willing to help with?
