### ISSUE TITLE
gzip

### ISSUE THREAD

**Issue by oi12344** [influxdata/influxdb-client-java#310]
hi, is The reativeApi supported gzip?

**Comment by bednar** [comment]
Hi @oi12344,

thanks for using our client.

> hi, is The reativeApi supported gzip?

Yes, you can enable `gzip` by:

```java
InfluxDBClientReactive client = InfluxDBClientReactiveFactory
        .create("http://localhost:8086", "my-token".toCharArray());

client.enableGzip();
```

Regards

**Comment by oi12344** [comment]
hi，Excuse me again! 
 I have a question，when use reactive batch send, Whether have it Timeout period, whatever it have collect data what batchSize set, it will send

**Comment by bednar** [comment]
Which version of the client do you use?

**Comment by oi12344** [comment]
4.3.0

**Comment by bednar** [comment]
How do you subscribe to `publisher` from `WriteReactiveApi`?

**Comment by bednar** [comment]
Can you share a little bit more about your code?

**Comment by oi12344** [comment]
`        // Write data
        //
        WriteReactiveApi writeApi = influxDBClient.getWriteReactiveApi(WriteOptionsReactive.builder().maxRetries(0).batchSize(5000).build());

        //
        // ReactiveStreams publisher
        //
        Publisher<WriteReactiveApi.Success> publisher = writeApi.writePoints(WritePrecision.S, source);`

I don't know if it's what you want？

**Comment by bednar** [comment]
In this configuration the `writeApi` prepare batches with 5_000 points. The batch will be sent in a subscription to `publisher`.

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
