### ISSUE TITLE
timestamp question

### ISSUE THREAD

**Issue by oi12344** [influxdata/influxdb-client-java#314]
```java        
InfluxDBClient influxDBClient = InfluxDBClientFactory.create("http://xxxxxx", token, org, bucket);

        //
        // Write data
        //
        WriteApiBlocking writeApi = influxDBClient.getWriteApiBlocking();
        Point point = Point.measurement("test").addTag("productId","800").addField("temperature",10).addField("deviceId",2).time(1636729543000L, WritePrecision.MS);
        writeApi.writePoint(point);

        influxDBClient.close();
```
i add timestamp, no exception ,but data is not insert influxdb

**Comment by bednar** [comment]
Hi @oi12344,

thanks for using our client.

The `1636729543000L` in `milliseconds` means `Monday, 10 March 1975 08:42:34.300`. 

Do you have correct time range in InfluxDB UI?

![image](https://user-images.githubusercontent.com/455137/158755526-6eebc900-cada-4897-9084-0d673709e460.png)


Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
