### ISSUE TITLE
InfluxDBClientFactory.create() params question

### ISSUE THREAD

**Issue by win434545299** [influxdata/influxdb-client-java#322]
__Steps to reproduce:__
I saw this code in InfluxDB, and the logLevel is not work.

1. String loglevel = "BODY"

2. InfluxDBClient client = InfluxDBClientFactory.create(String.format("%s:%s?readTimeout=%s&writeTimeout" +
                "=%s&connectTimeout=%s" +
                "&logLevel=%s", host, port, readTimeout, writeTimeout, connectTimeout, logLevel), token.toCharArray(), organization, bucket);

3.the logLevel is not work.

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version: 2.0
 - InfluxDB Version: 5.0.0
 - JDK Version: zulu1.8
 - Platform:macos

**Comment by bednar** [comment]
Hi @win434545299,

the connection string is supported only for: `public static InfluxDBClient create(@Nonnull final String connectionString)`. You have to use something like:

```java
String connectionString = String.format("%s:%s?readTimeout=%s&writeTimeout" +
        "=%s&connectTimeout=%s" +
        "&logLevel=%s&org=%s&bucket=%s&token=%s", "http://localhost", "8086", "10000", "10000", "10000", "BODY", "my-org", "my-bucket", "my-token");

InfluxDBClientFactory.create(connectionString);
```

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
