### ISSUE TITLE
flux-dsl to query command?

### ISSUE THREAD

**Issue by win434545299** [influxdata/influxdb-client-java#323]
__Steps to reproduce:__

 Flux flux = Flux.from("sample_variable")
            .filter(Restrictions.and(Restrictions.measurement().equal("variable")))
            .range(0L, ChronoUnit.SECONDS);

I print the flux , return this:
      from(bucket:"sample_variable")
	      |> filter(fn: (r) => (r["_measurement"] == "variable"))
	      |> range(start:0s)

__Expected behavior:__

I want to know, can I code like this:  influxDBClient.getQueryApi().query( flux )? I try change flux to String ,but I don't find this method...so , how can I use the flux object to query ?

__Specifications:__
 - Client Version: 2.0
 - InfluxDB Version:5.0.0
 - JDK Version:zulu 1.8
 - Platform: macOS

**Comment by bednar** [comment]
Hi @win434545299,

thanks for using our client.

> I try change flux to String ,but I don't find this method...so , how can I use the flux object to query ? Just use `toString()`:

```java
flux.toString();
```

Regards
