### ISSUE TITLE
Flux "not exists"

### ISSUE THREAD

**Issue by yoobi** [influxdata/influxdb-client-java#330]
__Proposal:__
Add of the `not` operator for Flux query 

__Current behavior:__
Couldn't find it in the doc or source code

__Desired behavior:__
```
Restrictions.value().exists().not()
```

__Use case:__
Useful for any Flux query.

**Comment by bednar** [comment]
Hi @yoobi,

thanks for using our client.

Currently the `flux-dsl` doesn't support `not exists` expression.

Is this something you might be willing to help with?

Regards

**Comment by yoobi** [comment]
I can take a look, but I'm not so proficient in Flux Language.
From what I've seen and understood the `not` needs to be added in the `ColumnRestriction.java` and in the `toString()` method. Could you confirm me that ?
Thank you !

**Comment by bednar** [comment]
The best way be to create new `Not` restriction, something like:

```
@Nonnull
    public static Restrictions not(@Nonnull final Restrictions restrictions) {
        return new Not(restrictions);
    }
```

at https://github.com/influxdata/influxdb-client-java/blob/5be7b5fb5d4046ab88907367c85fb787e8d9d492/flux-dsl/src/main/java/com/influxdb/query/dsl/functions/restriction/Restrictions.java#L42

The usage will be: `Restrictions.not(Restrictions.value().exists())`

**Comment by yoobi** [comment]
I've made a PR :)

**Comment by bednar** [comment]
Please, create PR into ` master ` branch.
