### ISSUE TITLE
[Question] How to get all tag keys from some bucket using Flux DSL?

### ISSUE THREAD

**Issue by mladen-djordjevic** [influxdata/influxdb-client-java#336]
Hello, 

At the moment, I am able to get all tag keys using query function: https://github.com/influxdata/influxdb-client-java/blob/master/client/src/main/java/com/influxdb/client/QueryApi.java#L59
with parameter:
`from(bucket: "telegraf/autogen")
    |> range(start: -30m)
    |> columns()
    |> keep(columns: ["_value"])
    |> group()
    |> distinct()`

Is there a better approach to get all unique tag keys from some bucket, ideally using Flux DSL builder?

Thank you in advance,
Mladen

**Comment by bednar** [comment]
Hi @mladen-djordjevic,

thanks for using our client.

Currently the `flux-dsl` doesn't supports the `columns()` function. As a workaround you can use `expression`:

```java
String flux = Flux
        .from("telegraf/autogen")
        .range(-30L, ChronoUnit.MINUTES)
        .expression("columns()")
        .keep(new String[]{"_value"})
        .group()
        .distinct()
        .toString();
```

Regards
