### ISSUE TITLE
The example in README.md needs to be updated

### ISSUE THREAD

**Issue by linghengqian** [influxdata/influxdb-client-java#340]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Open the README.md of each sub-client and try to execute its demo.

__Expected behavior:__
Describe what you expected to happen.

- The documentation example executes fine.

__Actual behavior:__
Describe What actually happened.

- After the release of `influxdb-client-java` 6.0.0, `RxJava` has switched to `3.x`, but most examples still use `io.reactivex.Flowable` instead of `io.reactivex.rxjava3.core.Flowable`. Use https://github.com/influxdata/influxdb-client-java/tree/v6.0.0/client-reactive#queries for example. This part needs to be adjusted to the new package.

- Maven dependencies are not specified in https://github.com/influxdata/influxdb-client-java/tree/v6.0.0/flux-dsl#flux-dsl like other clients. Need to be added.
- ![image](https://user-images.githubusercontent.com/20187731/164349683-c4e45576-b463-42a5-82fc-2e876bddb524.png)
- ![image](https://user-images.githubusercontent.com/20187731/164349721-76125630-2868-456c-ae9b-5996c53df9e1.png)
- Using the wrong API in https://github.com/influxdata/influxdb-client-java/tree/v6.0.0/client-reactive#construct-queries-using-the-flux-dsl-query-builder. `org.reactivestreams.Subscriber` is not a functional interface.
```java
queryApi
                .query(flux.toString())
                .subscribe(fluxRecord -> {
                    //
                    // The callback to consume a FluxRecord.
                    //
                    System.out.println(fluxRecord.getTime() + ": " + fluxRecord.getValueByKey("_value"));
                });
```
should be changed to
```java
queryApi
                .query(flux.toString())
                .subscribe(new Subscriber<>() {
                    @Override
                    public void onSubscribe(Subscription s) {

                    }

                    @Override
                    public void onNext(FluxRecord fluxRecord) {
                        //
                        // The callback to consume a FluxRecord.
                        //
                        System.out.println(fluxRecord.getTime() + ": " + fluxRecord.getValueByKey("_value"));
                    }

                    @Override
                    public void onError(Throwable t) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });
```
- `influxdb-spring` should join the configuration of Example in `application.properties` in SpringBoot to be more friendly to the user's prompt. Most people do not only use `Spring`.

__Specifications:__
 - Client Version: 6.0.0
 - InfluxDB Version: 2.2.0
 - JDK Version: 17.0.2
 - Platform: Windows

**Comment by bednar** [comment]
Hi @linghengqian,

thanks for using our client.

We will take a look.

Regards

**Comment by bednar** [comment]
> influxdb-spring should join the configuration of Example in application.properties in SpringBoot to be more friendly to the user's prompt. Most people do not only use Spring.

Can you please describe this in more detail? Thank you

**Comment by linghengqian** [comment]
> > influxdb-spring should join the configuration of Example in application.properties in SpringBoot to be more friendly to the user's prompt. Most people do not only use Spring.
> 
> Can you please describe this in more detail? Thank you

- I just found out that I confused `org.springframework.boot.autoconfigure.influx.InfluxDbProperties` with `com.influxdb.spring.influx.InfluxDB2Properties`, sorry to bother you. It looks like `spring-boot-autoconfigure-2.6.6.jar` has some legacy configuration from influxdb 1.x.
- 
![image](https://user-images.githubusercontent.com/20187731/164383794-bf182d20-0ca0-4555-89ca-2319582d8fc9.png)

- ![image](https://user-images.githubusercontent.com/20187731/164383705-8c5fa720-3feb-4464-ae43-a4ef945967e2.png)
