### ISSUE TITLE
FluxResultMapper toPojo not setting values to fields 

### ISSUE THREAD

**Issue by kalicja** [influxdata/influxdb-client-java#346]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create POJO ie:
`@Measurement(name = "measure_name")
public class SampleMeasure{

    @Column(timestamp = true)
    private Instant time;

    @Column(tag = true)
    private String tag;

    @Column
    private String field1;

    @Column
    private String field2;`

2. Write to influx 
List<SampleMeasure>m =new ArrayList() .....
`writeApi.writeMeasurements(bucket, organization, WritePrecision.MS, m);`
3. Read all with flux query
` Flux fluxQuery = Flux.from(bucket)
                .range(-356L, ChronoUnit.DAYS)
                .filter(Restrictions.and(Restrictions.measurement().equal('measure_name')));
return influxDBClient.getQueryApi().query(fluxQuery.toString(),SampleMeasure.class);`

__Expected behavior:__
returned List of SampleMeasure objects with field1, field2 set

__Actual behavior:__
returned  List of SampleMeasure objects with field1, field2 null, tags and time is set correctly 

__Specifications:__
 - Client Version: 5.0.0
 - InfluxDB Version: 2.2.0
 - JDK Version: 17
 - Platform: win 11

**Comment by bednar** [comment]
Hi @kalicja,

thanks for using our client.

You have to use [pivot() function](https://github.com/influxdata/influxdb-client-java/tree/master/flux-dsl#pivot).

```java
Flux fluxQuery = Flux
        .from(bucket)
        .range(-356L, ChronoUnit.DAYS)
        .filter(Restrictions.and(Restrictions.measurement().equal("measure_name")))
        .pivot()
            .withRowKey(new String[]{"_time"})
            .withColumnKey(new String[]{"_field"})
            .withValueColumn("_value");
```

Regards


Regards

**Comment by kalicja** [comment]
HI @bednar 
thx a lot, it works :D, it may be worth of adding it to examples?
