### ISSUE TITLE
creating/updating task with leading import statement not working

### ISSUE THREAD

**Issue by tost11** [influxdata/influxdb-client-java#351]
__Steps to reproduce:__

Create a task with leading import statement

```java
client.getTasksApi().createTaskCron("whatever",fluxQuery,"10 0 * * * *","01feb3ff2a370ff0");
```

fluxQuery like so:
```influx
import "experimental"

from(bucket: "user-1")
    |> range(start: experimental.addDuration(d: -1d, to: today()), stop: today())
    |> filter(fn: (r) => r["system"] == "2")
    |> filter(fn: (r) => r["_field"] == "ChargeWatt" or r["_field"] == "Duration")
    |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
    |> map(fn: (r) => ({r with _value: r.ChargeWatt * r.Duration / 1000.0 / 60.0}))
    |> cumulativeSum()
    |> max()
    |> map(fn: (r) => ({r with _time: today(), _measurement: "day-values", _field: "outcome"}))
```
It seems the flux query is generated wrong.
https://github.com/influxdata/influxdb-client-java/blob/19cf00f9059a09b0b376be1d28b7d0b6df536d59/client/src/main/java/com/influxdb/client/internal/TasksApiImpl.java#L724
The additional options seems to be added before the import statement:

```influx
option task = {name: "whatever", cron: "12 0 * * * *"}

import "experimental"

from(bucket: "user-1")
    |> ...
```
It should be:

```influx
import "experimental"

option task = {name: "whatever", cron: "12 0 * * * *"}

from(bucket: "user-1")
    |> ...
```

also the updateTask functions are not working

also could it be that on TaskCreateRequest the name attribute is missing some creation functions didn't work because of that

__Expected behavior:__
Create a new Task.

__Actual behavior:__
Error from influx because import statement is not allowed at this position
"invalid options: loc 2:2-2:8: invalid statement @2:2-2:8: import"

__Specifications:__
 - Client Version: 5.0.0
 - InfluxDB Version: 2.2
 - JDK Version: java-1.11.0-openjdk-amd64
 - Platform: Linux

**Comment by bednar** [comment]
Hi @tost11,

thanks for using our client.

> Error from influx because import statement is not allowed at this position
"invalid options: loc 2:2-2:8: invalid statement @2:2-2:8: import"

As a workaround please use the [TaskApi.createTask(@Nonnull final TaskCreateRequest taskCreateRequest)](https://influxdata.github.io/influxdb-client-java/influxdb-client-java/apidocs/com/influxdb/client/TasksApi.html#createTask-com.influxdb.client.domain.TaskCreateRequest-) method to create task. Something like following code will be works:

```java
String taskFlux = "import \"experimental\"\n"
        + "\n"
        + "option task = {name: \"whatever\", cron: \"12 0 * * * *\"}"
        + "\n"
        + "from(bucket: \"my-bucket\")\n"
        + "    |> range(start: experimental.addDuration(d: -1d, to: today()), stop: today())\n"
        + "    |> max()";

TaskCreateRequest taskCreateRequest = new TaskCreateRequest()
        .orgID(organization.getId())
        .flux(taskFlux)
        .status(TaskStatusType.ACTIVE);

Task task = tasksApi.createTask(taskCreateRequest);
```

> also could it be that on TaskCreateRequest the name attribute is missing some creation functions didn't work because of that

You have to specify the name in `option` part . The `TaskCreateRequest` definition doesn't contains `name` attribute - https://docs.influxdata.com/influxdb/v2.2/api/#operation/PostTasks.

Regards
