### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by AsurawithCross** [influxdata/influxdb-client-java#355]
https://github.com/influxdata/influxdb-client-java/issues/321#issue-1186057332

I also got this error in my test code , it seems like  when the value of the parameter is set to 0.0，it will become  java.lang.Long
![图片](https://user-images.githubusercontent.com/52518679/169980178-eecc0125-7930-4a52-8581-65aed0f87c41.png)

**Comment by bednar** [comment]
Hi @AsurawithCross,

thanks for using our client.

>  it seems like when the value of the parameter is set to 0.0

How do you write your data into InfluxDB? Is it written by `writeMeasurement`?

Regards

**Comment by bednar** [comment]
I've tested the following `POJO` and it is correctly to the `double` type:

```java
@Measurement(name = "pojoDouble")
private static class PojoDouble {

    @Column(name = "tag", tag = true)
    private String tag;

    @Column(name = "value")
    private Double value;
}
```

```java
PojoDouble pojo = new PojoDouble();
pojo.tag = "A";
pojo.value = 0.0;

String lineProtocol = mapper.toPoint(pojo, WritePrecision.S).toLineProtocol();
System.out.println(lineProtocol);
```

```
pojoDouble,tag=A value=0.0
```

> I also got this error in my test code , it seems like when the value of the parameter is set to 0.0，it will become java.lang.Long

Can you share your test case?

**Comment by bednar** [comment]
> Does this mean that I should not define two numeric fields?

No, the problem is in your query. You have to use the [pivot function()](https://docs.influxdata.com/flux/v0.x/stdlib/universe/pivot/) to arrange data in tabular way.
