### ISSUE TITLE
Can data types be returned when querying data instead of “object”？

### ISSUE THREAD

**Issue by DamonDBT** [influxdata/influxdb-client-java#356]
i heave a measurement have multiple column , the type of each column may be string, floating and other types. 
When querying the latest row of data use  "fluxRecord.getValue()",  all the returned column data type  are object, i need to convert type one by one . Can they be mapped to different data types like MySQL?

thanks.

influxdb-2.2
api-5.0.0
win 10

**Comment by bednar** [comment]
Hi @DamonDBT,

thanks for using our client.

If you would like to get strong-type results you have to use mapping to measurement. For more info see:

- https://github.com/influxdata/influxdb-client-java/tree/master/client#synchronous-query
- https://github.com/influxdata/influxdb-client-java/blob/master/examples/src/main/java/example/SynchronousQueryPojo.java

Regards

**Comment by DamonDBT** [comment]
Thank you for your answer.
 I tested a class with two double attributes. after query, I wanted to geta list<Common>, but failed. Here is my code.  

the define class ,have two fields  "air_press_all"、“air_temp_all”
 
 ```java
@Measurement(name = "common")
public class Common    {
	@Column(name = "air_press_all")
	Double air_press_all;
	@Column(name = "air_temp_all")
	Double air_temp_all;
	@Column(timestamp = true)
	Instant time;
}
```


i guess use   @Column(name = "air_press_all") to tell which column name in influxdb is right to  the prop of 'Common' **. is thak right?**

the query code :
 ```java
Restrictions restrictions = Restrictions.and(Restrictions.measurement().equal("common") );
char[]         tokenChar      = token.toCharArray();
InfluxDBClient influxDBClient = InfluxDBClientFactory.create(host, tokenChar, org, bucket);
QueryApi       queryApi       = influxDBClient.getQueryApi();
long start = -300;
long end   = 0;
Flux           flux           = Flux.from("cqe").range(start, end, ChronoUnit.SECONDS).filter(restrictions);
// List<InfluxVo> list = queryApi.query(flux.toString(), InfluxVo.class);
List<Common> list1 = queryApi.query(flux.toString(), Common.class);
influxDBClient.close(); 
```
  
but got error.
**is the query result class can only have one field value?**

**Comment by bednar** [comment]
> but got error. **is the query result class can only have one field value?**

No, you have to use the [pivot function()](https://docs.influxdata.com/flux/v0.x/stdlib/universe/pivot/):

```java
Flux flux = Flux.from("cqe")
                .range(start, end, ChronoUnit.SECONDS)
                .filter(restrictions)
                .pivot()
                    .withRowKey(new String[]{"_time"})
                    .withColumnKey(new String[]{"_field"})
                    .withValueColumn("_value");
```

**Comment by DamonDBT** [comment]
thanks for your help ,  
 i got the result. here is how i do ,maybe help to others.

![1](https://user-images.githubusercontent.com/19727006/170403112-26004246-ff7d-43fe-9b23-f6437a24517d.jpg)

```java
// @Measurement(name = "common")
public  class Common
{
    // @Column
    Double airPressAll;

    // @Column
    Double air_temp_all;

  // both name method is ok .

    // @Column(timestamp = true)
    Instant time;
}
```
the query flux:
```java
 Flux flux = Flux.from("cqe").range(start, end, ChronoUnit.SECONDS).filter(restrictions).pivot()
                .withRowKey(new String[]{"_time"})
                .withColumnKey(new String[]{"_field"})
                .withValueColumn("_value"); 
List<Common> query = queryApi.query(flux.toString(), Common.class);
 
```
and got the pojo result:

![2](https://user-images.githubusercontent.com/19727006/170403131-3e044600-039e-4bd8-8fee-0feabbbdd813.jpg)
