### ISSUE TITLE
SpringBoot @Measurement Annotation not recognized. 

### ISSUE THREAD

**Issue by amra2803** [influxdata/influxdb-client-java#374]
I am trying to create a POJO by following the example provided here:

```
  @Measurement(name = "temperature")
    public static class Temperature {

        @Column(tag = true)
        String location;

        @Column
        Double value;

        @Column(timestamp = true)
        Instant time;
    }
```

When I do this with IntelliJ the @Measurement annotation is not recognized. 

![afbeelding](https://user-images.githubusercontent.com/99823471/177991485-635f9378-11cf-4ffe-8b64-cbcf3eb44c9d.png)

**Comment by bednar** [comment]
Hi @amra2803,

thanks for using our client.

Do you use correct import for the `@Measurement` class - `import com.influxdb.annotations.Measurement;` ?

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
