### ISSUE TITLE
Where can i download a compiled .jar file?

### ISSUE THREAD

**Issue by jayjupdhig** [influxdata/influxdb-client-java#375]
Where can i download a compiled .jar file?

Can't see something like that in the "Release" section. Why?

**Comment by jayjupdhig** [comment]
where to post my issue here: https://github.com/influxdata/influxdb-java/issues/853 

or HERE?

**Comment by bednar** [comment]
Hi @jayjupdhig,

you can download the jars from Maven repository:

https://mvnrepository.com/artifact/com.influxdb/influxdb-client-java/6.3.0

Regards

**Comment by jayjupdhig** [comment]
Thank you very much - solved! :-)
