### ISSUE TITLE
500 points and 50 concurrent readtimeout，Does incluxdb client java have thread restrictions or tag restrictions？

### ISSUE THREAD

**Issue by yongjingwei** [influxdata/influxdb-client-java#378]
When I use 5000 points to cut into 500 points, that is, 10 threads to request the query, the query results can be found. But when I use this interface to query simultaneously with 5 requests, that is, 10 * 5 concurrent requests, it is always read timeout. No matter how much readtime I configure, it doesn't work. Is this the reason why there are too many point requests and too many connections? How to adjust it

**Comment by bednar** [comment]
Hi @yongjingwei,

thanks for using our client.

Can you be a little more specific how you using the client. Do you use one instance of the client? 

The timeout error is from server … do you have proper size of your server?

https://docs.influxdata.com/influxdb/v1.8/guides/hardware_sizing/#influxdb-oss-guidelines

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
