### ISSUE TITLE
The Internet security department scans for web address vulnerabilities

### ISSUE THREAD

**Issue by kigangka** [influxdata/influxdb-client-java#397]
Influxdb2，Company network security scan out "http://ip:8086/debug/pprof/goroutine?Debug =1 "can be accessed directly without permission, and it is considered as a vulnerability. How to shield it?
![screenshots](https://user-images.githubusercontent.com/31200174/183809760-1a5f4fb3-08f2-4853-9293-df9478f2a07f.jpg)

**Comment by bednar** [comment]
You can use `[pprof-disabled](https://docs.influxdata.com/influxdb/v2.3/reference/config-options/#pprof-disabled)` configuration option - https://docs.influxdata.com/influxdb/latest/reference/config-options/?t=JSON#pprof-disabled
