### ISSUE TITLE
Prepare release to Maven central repository

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-java#40]
[OSSRH Guide](https://central.sonatype.org/pages/ossrh-guide.html)

- [x] Repackage from `org.influxdata` to `com.influxdb.client`
- [x] Update `README.md`
- [x] Update `pom.xml`
- [x] Complete [OSS Requirements](https://central.sonatype.org/pages/requirements.html)
   - [x] _If, for some reason (for example, license issue or it's a Scala project), you can not provide -sources.jar or -javadoc.jar , please make fake -sources.jar or -javadoc.jar with simple README inside to pass the checking._
   - [x] _Project Name, Description and URL_
   - [x] _License Information_
   - [x] _Developer Information_
   - [x] _SCM Information_
- [x] Change version to `1.0.0.M2-SNAPSHOT` - according to [Spring Versioning](https://github.com/spring-projects/spring-framework/wiki/Spring-Framework-Artifacts#milestones-and-release-candidates) and our issue milestone
- [x] Deploy snapshots to [OSS Snapshot repository](https://oss.sonatype.org/content/repositories/snapshots/)
   - [x] Create a New Project ticket
   - [x] [TXT record verification](https://central.sonatype.org/pages/producers.html)
- [x] Remove `bonitoo-repository` from `pom.xml`
- [x] Refactor [influxdata-iot-petstore](https://github.com/bonitoo-io/influxdata-iot-petstore)
- [x] Refactor [flux-unit-tests](https://github.com/bonitoo-io/flux-unit-tests)

@alextavgen

**Comment by bednar** [comment]
[Create a New Project ticket](https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134)

- `Summary`: The InfluxDB 2.0 JVM Based Clients
- `Group Id`: com.influxdb
- `Project URL`: https://github.com/bonitoo-io/influxdb-client-java
- `SCM url`: https://github.com/bonitoo-io/influxdb-client-java.git

**Comment by ivankudibal** [comment]
FYI, the request https://issues.sonatype.org/browse/MVNCENTRAL-5026
