### ISSUE TITLE
Add getTime() to com.influxdb.client.write.Point

### ISSUE THREAD

**Issue by derpeter** [influxdata/influxdb-client-java#411]
__Proposal:__
By adding a getter for the timestamp a developer can get more control on handling data points.
E.g. on handling the storing and retry of points in case of an not reachable InfluxDB. 

__Current behavior:__
getter does not exists and value is private / class is final so there is no nice way to access the value

__Desired behavior:__
Calling point.getTime() to get the Timestamp

__Alternatives considered:__
Not declaring the Point class as final would allow to extend the Point class 

__Use case:__
In my case collect values from a number of APIs into Points on Android. Points are can either go live to the InfluxDB and/or be cached into a local DB to be send when the connection to the DB is possible. Using the Timestamp to identify the points would be very helpful.

**Comment by bednar** [comment]
Hi @derpeter,

thanks for using our client.

> **Desired behavior:**
> Calling point.getTime() to get the Timestamp

Is this something you might be willing to help with?

Regards

**Comment by derpeter** [comment]
Hey, i can try to look into it, as java and the whole maven eco system are not my strong suite it might take a while

**Comment by bednar** [comment]
@derpeter the PR is already prepared for review - https://github.com/influxdata/influxdb-client-java/pull/419, I assume that the fix will be available in next stable release

**Comment by derpeter** [comment]
thats awesome, thanks alot
