### ISSUE TITLE
How to get measurements in buckets?

### ISSUE THREAD

**Issue by blackstar-baba** [influxdata/influxdb-client-java#415]
__Proposal:__
I want get measurements in buckets.

__Current behavior:__
I  can't find api to get measurements.

__Desired behavior:__
Add measurements management api for getting.

**Comment by bednar** [comment]
Hi @blackstar-baba,

thanks for using our client.

You have to use `QueryApi` with corresponding `flux` function - [schema.measurements()](https://docs.influxdata.com/flux/v0.x/stdlib/influxdata/influxdb/schema/measurements/).

Regards

**Comment by blackstar-baba** [comment]
3ks @bednar
