### ISSUE TITLE
Instance of InfluxDBClient fails NullPointer exception when calling usersApi.me()

### ISSUE THREAD

**Issue by Assimilator** [influxdata/influxdb-client-java#429]
Essentially, I'm trying to see if I'm properly authenticated on the client-side. Currently I instantiate my InfluxDBClient then instantiate my UsersApi. When authentication is successful usersApi.me() returns the User instance properly, when it is not, I get a NullPointer exception. The reason I am doing this check is because when the token is wrong WriteApi instance fails completely silently on writing points.

Am I doing my authentication check completely wrong or is there some sort of feedback in WriteApi that I am missing?

__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. use wrong authentication token
2. create an instance of InfluxDBClient 
3. usersApi = influxDBClientInstance.getUsersApi()
4. User user = usersApi.me()

__Expected behavior:__
Return value is null

__Actual behavior:__
usersApi.me() fails with a NullPointer exception

__Specifications:__
 - Client Version: influxdb-client-java 4.3.0 (I checked the code of the latest client and there is no difference between the latest version and 4.3.0)
 - InfluxDB Version: 2.2.0
 - JDK Version: 18.0.2
 - Platform: Ubuntu 22.04 LTS

**Comment by bednar** [comment]
Hi @Assimilator,

thanks for using our client.

We will take a look.

Regards

**Comment by bednar** [comment]
Hi @Assimilator,

I've tried following example with wrong token and client correctly throws `UnauthorizedException`:

```
package example;

import java.util.logging.Logger;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.domain.User;
import com.influxdb.exceptions.UnauthorizedException;

public class PlatformExample {

    private static final Logger LOG = Logger.getLogger(PlatformExample.class.getName());

    public static void main(final String[] args) throws Exception {

        String url = "http://localhost:9999";
        String token = "my-token-not-exists";
        
        try (InfluxDBClient client = InfluxDBClientFactory.create(url, token.toCharArray())) {
            try {
                User me = client.getUsersApi().me();
                LOG.info("Successfully authenticated user: " + me);
            } catch (UnauthorizedException e) {
                LOG.severe("Cannot authorize with token: " + token);
            }
        }

    }
}
```

* InfluxDB Version: 2.4.0
* Client Version: 6.6.0

Can you test your code with updated versions?

Regards

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.

**Comment by Assimilator** [comment]
@bednar tested it with the updated version, the issue has been fixed, thank you!

**Comment by bednar** [comment]
@Assimilator you are welcome
