### ISSUE TITLE
`scoverage-maven-plugin` is not compatible with 2.13.9

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-java#433]
We can't update the Scala `2.13.x` version to the `2.13.9` because this version is not supported by https://github.com/scoverage/scoverage-maven-plugin/issues/106. 

We have to figure out how to deal with that because there is a security issue for Scala 2.13.8 - https://github.com/influxdata/influxdb-client-java/security/dependabot/1

**Comment by dalbani** [comment]
It's not clear to me why Scala version `2.13.9` in particular introduces this incompatibility. Where does this comes from?

**Comment by bednar** [comment]
@dalbani 

`scoverage-maven-plugin` plugin depends on `org.scoverage:scalac-scoverage-plugin:1.4.11`. The `org.scoverage:scalac-scoverage-plugin` doesn't have deployed build for `Scala 2.13.9`:

![image](https://user-images.githubusercontent.com/455137/193210484-bc2fffd6-a50b-46cb-9b34-ed781f2b1ffa.png)

https://mvnrepository.com/artifact/org.scoverage/scalac-scoverage-plugin

**Comment by dalbani** [comment]
I see, thanks for the info!
