### ISSUE TITLE
Missing setter method Authorization.setUserID(String)?

### ISSUE THREAD

**Issue by grillbaer** [influxdata/influxdb-client-java#453]
Thank you for your great java client implementation. I think i found a small issue:

Looks like the required setter method `Authorization.setUserID(String)` is missing.
Could you please add it (or am i getting the topic wrong)?

__Steps to reproduce:__

Compare API spec  [Create an authorization](https://docs.influxdata.com/influxdb/v2.4/api/#operation/PostAuthorizations) request body field `userID` with the corresponding class implementation field in `Authorization`.

__Expected behavior:__

In order to create an authorization scoped to an user with the request `AuthorizationsApi.createAuthorization(Authorization)`, the `Authorization` object needs its `userID` field to be set according to API docs.

__Actual behavior:__

There is no setter for field `Authorization.userID`.

__Specifications:__

 - Client Version: 6.6.0
 - InfluxDB Version: 2.4
 - JDK Version: not relevant
 - Platform: not relevant

**Comment by bednar** [comment]
Hi @grillbaer,

thanks for using our client. 

The InfluxDB API uses `AuthorizationPostRequest` as an object for create `Authorization` - https://github.com/influxdata/openapi/blob/b561645e05716036f071a43df0bf2a81ad32be90/contracts/oss.yml#L10182. 

I will update our API to supports create `Authorization` by `AuthorizationPostRequest`. Meanwhile you can use following workaround:

```java
package example;

import java.io.IOException;
import java.util.Collections;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.domain.Authorization;
import com.influxdb.client.domain.AuthorizationPostRequest;
import com.influxdb.client.domain.Permission;
import com.influxdb.client.domain.PermissionResource;
import com.influxdb.client.service.AuthorizationsService;

import retrofit2.Call;

public class InfluxDB2ManagementExample {

    public static void main(final String[] args) throws IOException {

        try (InfluxDBClient client = InfluxDBClientFactory.create("http://localhost:8086", "my-token".toCharArray())) {

            String orgID = "my-org-id";
            String userID = "my-user-id";

            PermissionResource userResource = new PermissionResource()
                    .orgID(orgID)
                    .type(PermissionResource.TYPE_USERS);

            Permission readUsers = new Permission()
                    .action(Permission.ActionEnum.READ)
                    .resource(userResource);

            AuthorizationPostRequest request = new AuthorizationPostRequest();
            request
                    .orgID(orgID)
                    .userID(userID)
                    .permissions(Collections.singletonList(readUsers))
                    .status(AuthorizationPostRequest.StatusEnum.ACTIVE);

            AuthorizationsService service = client.getService(AuthorizationsService.class);

            Call<Authorization> call = service.postAuthorizations(request, null);

            System.out.println("created = " + call.execute().body());
        }
    }
}
```

Regards

**Comment by grillbaer** [comment]
Hi @bednar, thank you for your support!

Great, using the `AuthorizationPostRequest` directly also makes clear which fields will have an effect (orgID, userID, ...) and which fields of `Authorization` would not (org, user).
I'll use your workaround.
