### ISSUE TITLE
Unable to create @Body converter for class com.influxdb.client.domain.Query

### ISSUE THREAD

**Issue by silas229** [influxdata/influxdb-client-java#465]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. Create a new bucket
2. Execute sample query code provided generated by InfluxDB

__Expected behavior:__
Execute the query and return the result

__Actual behavior:__
Error message when I execute `client.getQueryApi().query(query);`:
```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to create @Body converter for class com.influxdb.client.domain.Query (parameter #6)
    for method QueryService.postQueryResponseBody
```
Adding data works like a charm :)

__Specifications:__
 - Client Version: 6.7.0
 - InfluxDB Version: 2.4.0
 - JDK Version: 17
 - Platform: macOS

**Comment by bednar** [comment]
Hi @silas229,

thanks for using our client.

It looks like problem with `gson` version. Can you check the version of `gson` library on your classpath? The client depends on `2.10`.

Regards

**Comment by silas229** [comment]
I don't think I have any version of gson installed. Isn't the library installed as a dependency when I install `influxdb-client-java` via maven?

**Comment by bednar** [comment]
> I don't think I have any version of gson installed. Isn't the library installed as a dependency when I install influxdb-client-java via maven?

Yes, it is. Unfortunately there could be conflict with requirements from other libraries.
