### ISSUE TITLE
write fail when using username password based influxdb java client

### ISSUE THREAD

**Issue by sw-alpha-romeo** [influxdata/influxdb-client-java#469]
__Steps to reproduce:__
execute below code by changing host, user name and password

`

       InfluxDBClientOptions influxDBClientOptions = InfluxDBClientOptions.builder().url("").authenticate("admin", "helloworld".toCharArray()).bucket("test").org("my-org").build();

       InfluxDBClient client = InfluxDBClientFactory.create(influxDBClientOptions);  
       
        WriteApi writeApi = client.getWriteApi()) 

        Point point = Point.measurement("mem")
                    .addTag("host", "host3")
                    .addField("used_percent3", 29.43234543);

        writeApi.writePoint(point);
        client.close();
`

__Expected behavior:__
expected that successful write will have happen

__Actual behavior:__
Getting unauthorized access error
com.influxdb.exceptions.UnauthorizedException: unauthorized access
Note:- 
1> Using same credentials which I used in the code, I am able to login to InfluxDB web UI console.
2> If I create a token from web UI console after login using credentials used in the code and use
this new token then in InfluxDBClientOptions, then write operation gets successful
__Specifications:__
 - Client Version: 
 - InfluxDB Version: 2.5
 - JDK Version: 11
 - Platform: mac

**Comment by bednar** [comment]
Hi @sw-alpha-romeo,

thanks for using our client.

The `WriteApi` uses background thread to batch writes into InfluxDB, so you have to close `writeApi` before closing the client. The following code will works:

```java
package example;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.InfluxDBClientOptions;
import com.influxdb.client.WriteApi;
import com.influxdb.client.write.Point;

public class InfluxDB2Example {

    public static void main(final String[] args) {

        InfluxDBClientOptions influxDBClientOptions = InfluxDBClientOptions.builder()
                .url("http://localhost:9999")
                .authenticate("my-user", "my-password".toCharArray())
                .bucket("my-bucket")
                .org("my-org")
                .build();

        try (InfluxDBClient client = InfluxDBClientFactory.create(influxDBClientOptions)) {

            try (WriteApi writeApi = client.makeWriteApi()) {

                Point point = Point.measurement("mem")
                        .addTag("host", "host3")
                        .addField("used_percent3", 29.43234543);

                writeApi.writePoint(point);
            }
        }
    }
}
```

or you can you `WriteApiBlocking`:

```java
package example;

import com.influxdb.client.InfluxDBClient;
import com.influxdb.client.InfluxDBClientFactory;
import com.influxdb.client.InfluxDBClientOptions;
import com.influxdb.client.WriteApiBlocking;
import com.influxdb.client.write.Point;

public class InfluxDB2Example {

    public static void main(final String[] args) {

        InfluxDBClientOptions influxDBClientOptions = InfluxDBClientOptions.builder()
                .url("http://localhost:9999")
                .authenticate("my-user", "my-password".toCharArray())
                .bucket("my-bucket")
                .org("my-org")
                .build();

        try (InfluxDBClient client = InfluxDBClientFactory.create(influxDBClientOptions)) {

            WriteApiBlocking writeApi = client.getWriteApiBlocking();

            Point point = Point.measurement("mem")
                    .addTag("host", "host3")
                    .addField("used_percent3", 29.43234543);

            writeApi.writePoint(point);
        }
    }
}
```

btw the recommended authentication is by `token`.

Regards
