### ISSUE TITLE
Query API url outdated

### ISSUE THREAD

**Issue by mashintsev** [influxdata/influxdb-client-java#48]
Url in influxd 2.0.0-alpha.16 - http://localhost:9999/api/v2/query?**org**=my-org
Url in java client - http://localhost:9999/api/v2/query?orgID=my-org

When send request to old url got error - 
```
{
    "code": "invalid",
    "message": "failed to decode request body",
    "op": "http/handlePostQuery",
    "error": {
        "code": "invalid",
        "message": "id must have a length of 16 bytes"
    }
}
```

**Comment by bednar** [comment]
Hi @mashintsev,

Thanks for using **InfluxDB 2.0** and **influxdb-client-java**. 

The `QueryAPI` currently use `orgID` parameter for queries to InfluxDB 2.0.

The InfluxDB 2.0.0-alpha.16 is not able to handle organization name and organization ID as an `org` parameter - see https://github.com/influxdata/influxdb/issues/13906.

Please try use `QueryAPI` with organization ID and We will prepare workaround that our API will be accept both - organization name and organization ID.

**Comment by mashintsev** [comment]
Thanks for your answer.

**Comment by bednar** [comment]
Prepared PR into InfluxDB: https://github.com/influxdata/influxdb/pull/14540

**Comment by bednar** [comment]
The latest nightly build supports the interchangeability between name and org. Before releasing InfluxDB `v2.0.0-alpha.17` you can try the nightly build:

```bash
docker pull quay.io/influxdb/influxdb:nightly
```
