### ISSUE TITLE
WriteParameters#hashCode can produce NPE

### ISSUE THREAD

**Issue by frederic-pierre** [influxdata/influxdb-client-java#482]
Hi there,

The method `com.influxdb.client.write.WriteParameters#hashCode` can produce a `NullPointerException` if the `bucket` or the `org` is `null`.

As we set those two properties in the `InfluxDBClientOptions`, we're not setting them in the `WriteParameters`. This should not lead to potential NPE.

__Specifications:__
 - Client Version: 6.7.0
 - InfluxDB Version: 2.5.1
 - JDK Version: 17.0.5

**Comment by bednar** [comment]
Hi @frederic-pierre,

thanks for report this issue. We will take a look.

Regards
