### ISSUE TITLE
influxdb-spring is not compatible with SpringBoot 3

### ISSUE THREAD

**Issue by yikuo123** [influxdata/influxdb-client-java#518]
The auto-configuration is not loaded

> If you have created your own auto-configurations, you should move the registration from spring.factories under the org.springframework.boot.autoconfigure.EnableAutoConfiguration key to a new file named META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports. Rather than a single comma-separate list, each line contains the fully qualified name of an auto-configuration class

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files

**Comment by bednar** [comment]
Hi @yikuo123,

the version `6.8.0` released at `2023-03-29` already supports new syntax for `auto-configuration` - https://github.com/influxdata/influxdb-client-java/pull/470

Regards
