### ISSUE TITLE
Requesting an feature Availability

### ISSUE THREAD

**Issue by VIJ17** [influxdata/influxdb-client-java#533]
1) Is there any way to do Replication for whole server in InfluxDB?
If available, please help me to how to do that.

2) During failover senarios, is there any way to do all my bucket replications in master server to slave server? Not by creating replication streams to every buckets individually. Because If there is 100's of buckets in a server, it was a big headover to do replication for all those buckets. Instead of that it will be easy if any feature available to replicate all those buckets by giving a pattern or something like that.
Someone please help me to shortout this issue.

**Comment by bednar** [comment]
Hi @VIJ17,

the java client is not responsible for replication. You have to use InfluxDB enterprise - https://www.influxdata.com/products/influxdb-enterprise/

Regards
