### ISSUE TITLE
@Column(name="xxxx")Unable to work

### ISSUE THREAD

**Issue by aeasylife** [influxdata/influxdb-client-java#538]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. I have a demo for querying pojo. However, the 'spendMs' field in the result cannot be obtained. The @ Column (name="spend ms") I used doesn't seem to be effective
![image](https://user-images.githubusercontent.com/20423987/235067427-19f19f22-745d-4765-805f-fdb2b4d4ba01.png)
![image](https://user-images.githubusercontent.com/20423987/235069479-cbb4d56a-924a-47e1-a40c-86827d5ce08b.png)
![image](https://user-images.githubusercontent.com/20423987/235069581-f1adc2a0-d83b-46c0-857e-53059f855960.png)

2. This is the information I found through debugging, it seems that my 'name' can only be fixed to configure 'value'.
![image](https://user-images.githubusercontent.com/20423987/235067860-6883254d-8a1d-40d4-bfe6-5c3b5a8d9733.png)
![image](https://user-images.githubusercontent.com/20423987/235067965-5251b073-7d3a-4812-a7af-d77401f007c3.png)

 I want to know if there was a mistake in my approach

__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version: v6.8.0
 - InfluxDB Version: v2.7
 - JDK Version: 8

**Comment by aeasylife** [comment]
https://github.com/influxdata/influxdb-client-java/pull/516
  I saw a rejected fix that seemed to be repairable

**Comment by bednar** [comment]
Hi @aeasylife,

how looks like query output from InfluxDB?

Regards

**Comment by aeasylife** [comment]
> Hi @aeasylife,
> 
> how looks like query output from InfluxDB?
> 
> Regards
If I use @ Column (name="spend ms") , the result is null,
if it is @ Column (name="value"), I can get the correct value.
![image](https://user-images.githubusercontent.com/20423987/236105774-8771db76-f908-4e4e-bdd3-c9b0705238fb.png)
![image](https://user-images.githubusercontent.com/20423987/236105933-3f3c86c5-767b-4c4f-9cf7-7d1af00c9bb9.png)
![image](https://user-images.githubusercontent.com/20423987/236104773-34ee6be5-28dd-41fb-bdc4-0abd1f7ba0c5.png)
![image](https://user-images.githubusercontent.com/20423987/236104983-10879f34-d5fc-4969-a311-7dbd4ac985c6.png)
![image](https://user-images.githubusercontent.com/20423987/236105181-c9b25b43-f905-4ffc-afa3-b94fe90cf564.png)
This is a test that writes 10000 'line protocols' per second, and reads part of the data every 10 seconds for nearly a minute, The duration of each read/write record is recorded
![image](https://user-images.githubusercontent.com/20423987/236105650-761da6f4-bdc7-4738-8db4-4fff1226efcc.png)

**Comment by bednar** [comment]
Hi @aeasylife,

You have to use `pivot` function - https://docs.influxdata.com/flux/v0.x/stdlib/universe/pivot/

Regards

**Comment by sjoshid** [comment]
@bednar 
What does `pivot` has anything to do with the bug being reported?

**Comment by bednar** [comment]
@sjoshid the current implementation of the POJO mapper is designed with the expectation that data returned from a query is structured in a uniform tabular format, where each row corresponds to a POJO and each column corresponds to a field within the POJO. This tabular structure is essential for the mapper to correctly associate database fields with the corresponding fields in the POJO.

However, without using the pivot function in your query, each field is returned as a separate table. This results in a fragmented data structure where the mapper cannot correctly associate and deserialize the data into POJOs because it expects all fields for a single object to be in the same table or the same part of the result set.

**Comment by sjoshid** [comment]
Is this example wrong? https://github.com/influxdata/influxdb-client-java/blob/master/examples/src/main/java/example/FluxClientPojoExample.java

**Comment by bednar** [comment]
@sjoshid the mapped `Cpu` class contains only one field that is mapped to the `_value` column from the response, which is the primary reason it works correctly. 

```java
package example;

import java.time.Instant;

import com.influxdb.annotations.Column;

import org.apache.commons.lang3.builder.ReflectionToStringBuilder;

public class Cpu {

    @Column(timestamp = true)
    Instant time;

    @Column(name = "_value")
    double usage;

    String host;

    @Override
    public String toString() {
        return ReflectionToStringBuilder.toString(this);
    }
}
```

**Comment by sjoshid** [comment]
I still don't know what you are getting at. 

But, the more I talk to you more I hate Flux and want to say horrible  things about it. So I'll just stop. 

Thanks for the explanation.
