### ISSUE TITLE
[v6.8.0/v6.9.0]401 error occurs when the network is disconnected and cannot be automatically restored

### ISSUE THREAD

**Issue by kervin521** [influxdata/influxdb-client-java#611]
__Steps to reproduce:__
List the minimal actions needed to reproduce the behavior.

1. ...
2. ...
3. ...

**### v6.7.0 is OK**
__Expected behavior:__
Describe what you expected to happen.

__Actual behavior:__
Describe What actually happened.

__Specifications:__
 - Client Version: 6.8.0/6.9.0
 - InfluxDB Version: 2.4.0
 - JDK Version: 1.8
 - Platform: Linux (Ubuntu 20.04)
 - Docker: 20.10.2

**Comment by bednar** [comment]
You have to use token authorization.
