### ISSUE TITLE
Documentation: README.md documents example that should be improved

### ISSUE THREAD

**Issue by ivankudibal** [influxdata/influxdb-client-java#62]
The current README.md code documents classes that were renamed. 
```
        RetentionRule retention = new RetentionRule();
        retention.setEverySeconds(3600L);
```

Correct example is:

```
        BucketRetentionRules bucketRetentionRules = new BucketRetentionRules();
        bucketRetentionRules.setEverySeconds(3600L);
````

It would also be nice to document here the default RP, and how I as a user can set up the autogen policy.

**Comment by bednar** [comment]
Examples are fixed and I also added sources for them: [examples/src/main/java/example](https://github.com/influxdata/influxdb-client-java/tree/master/examples/src/main/java/example).
