### ISSUE TITLE
please consider support GraalVM native-image 

### ISSUE THREAD

**Issue by pigeon2049** [influxdata/influxdb-client-java#672]
__Proposal:__
Short summary of the feature.

MissingReflectionRegistrationUtils.forProxy
com.influxdb.client.service.HealthService 

please consider add native support 
https://github.com/oracle/graalvm-reachability-metadata

thank you
__Current behavior:__
Describe what currently happens.

__Desired behavior:__
Describe what you want.

please consider add native support 
https://github.com/oracle/graalvm-reachability-metadata

__Alternatives considered:__
Describe other solutions or features you considered.

__Use case:__
Why is this important (helps with prioritizing requests)?

**Comment by bednar** [comment]
Hi @pigeon2049,

thanks for your suggestions.

Is this something you would be willing to help with? All PR is welcome and we will be happy to review your submission.

Regards
