### ISSUE TITLE
WriteApi seems to throw no exceptions and write no data

### ISSUE THREAD

**Issue by kadhikary** [influxdata/influxdb-client-java#71]
I tried with empty token strings, empty buckets strings, whatever. No exceptions, tests ran to success. The DeleteAPI however threw exceptions.

With correct token and bucket strings, the writeApi tests ran to success, but no data was written in the cloud Data Explorer.

I  am using version 1.2.0, 

Any hints as to any library I may be missing ?! Don't think so,

**Comment by kadhikary** [comment]
Please ignore. I forgot to do writeApi.flush(). This should be written somewhere in examples.
It still does not seem to write data to the cloud bucket, but this issue is not relevant.

**Comment by bednar** [comment]
Hi @kadhikary,

`WriteApi` writes by batches that are configured via `WriteOptions`.  If you would like write by synchrounous blocking way you could use `WriteApiBlocking`.


- https://github.com/influxdata/influxdb-client-java/blob/c26389867091ab5782a61a754b5bbdcdf7cf9298/client/src/main/java/com/influxdb/client/WriteApi.java#L46
- https://github.com/influxdata/influxdb-client-java/blob/c26389867091ab5782a61a754b5bbdcdf7cf9298/client/src/main/java/com/influxdb/client/WriteOptions.java#L53
- https://github.com/influxdata/influxdb-client-java/blob/c26389867091ab5782a61a754b5bbdcdf7cf9298/client/src/main/java/com/influxdb/client/WriteApiBlocking.java#L41

Regards
