### ISSUE TITLE
High Throughput Batched Async Writes Lost

### ISSUE THREAD

**Issue by jujo1** [influxdata/influxdb-client-java#73]
Use case: 
Batch loading many flat files equating in total to many TBs of data into influx.  

Replication: 
Threadpool of N Client and WriteApi processing N files in parallel. The batch size is 5000. Parsing the raw data into Points at a throughput is 1M Points/s which are queued and a copy of this queue is submitted to the writer once the queue has reached the batch size. Tags are alphabetically ordered, a write precision of ns is used with an increment of 1 ns for every element within a batch to guarantee uniqueness. 

Problem: 
1. Initially, each batch write is followed with a WriteSuccessEvent is received, however, after several batches this appears to stop. No write errors or warns are received. 
2. Points written are not written to the influx and no error or warn is received for these points. These points appear to have been lost.
3. If N=1 the problem still exists and appears related to throughput.
4. WriterApi appears to not create a copy the list of Points given to it which means if the producer is faster than the writer then there is a race condition on the list of Points (i.e. if it is cleared).

Questions:
1. Is it possible to batch write 1M/s, (with acceptable latency tolerance for influx processing) and if different to above what is the correct use of this client?
2. Where are the missing points; how can I turn on influx verbose logging?

**Comment by rhajek** [comment]
Hi, thank you for the feedback and describing your use case. 

We are going to add example, which will demonstrate the maximal write throughput (using RxJava (multiple threads), random generated data or parse CSV) to find the bottleneck and limits. In our current benchmark we are able to to write 200k Points/s (on AMD Ryzen 7 3700X 8-Core) but that benchmark is not optimized to get maximal throughput.

Verbose logging of HTTP client call can be enabled by:
```
client.setLogLevel(LogLevel.BASIC);
```

**Comment by bednar** [comment]
This issue has been closed because it has not had recent activity. Please reopen if this issue is still important to you and you have additionally information.
