### ISSUE TITLE
Null returned instead of empty result in `InfluxQLQueryApi.query()`

### ISSUE THREAD

**Issue by marcinkoziarz** [influxdata/influxdb-client-java#744]
__Steps to reproduce:__

1. Start empty Influxdb instance
2. Create bucket named "myBucket"
3. Request list of elements `InfluxQLQueryResult result = client.getInfluxQLQueryApi().query(new InfluxQLQuery("show field keys", "myBucket"));`

__Expected behavior:__
Code above should return empty result: `result.getResults()` should return an empty `List`.

__Actual behavior:__
Code returns null, despite method `query(...)` being annotated `@NonNull`.

__Specifications:__
 - Client Version: `7.1.0`
 - InfluxDB Version: `v2.7.6`
 - JDK Version: `openjdk 17.0.11 2024-04-16`
 - Platform: `ArchLinux 6.9.5-arch1-1`

I believe error is somewhere in `AbstractQueryApi` class, in bodyConsumer (lines 118+):
```
        BufferedSource source = body.source();

        while(source.isOpen() && !source.exhausted() && !cancellable.wasCancelled) {
          // consumer won't be executed when body is empty
          consumer.accept(cancellable, source);
        }
```

**Comment by bednar** [comment]
Hi @marcinkoziarz,

Thank you for reporting this issue. We will address it in PR #733.

Best regards
