### ISSUE TITLE
Use of exists operator 

### ISSUE THREAD

**Issue by lujop** [influxdata/influxdb-client-java#75]
It's possible to use the [`exists` operator](https://v2.docs.influxdata.com/v2.0/query-data/guides/exists/)?

I looked at current Restrictions implementation and I don't know how to use it.

**Comment by bednar** [comment]
Hi @lujop,

The issue is fixed in [1.4.0 milestone](https://github.com/influxdata/influxdb-client-java/milestone/7). 

If you would like to use a preview version use our snapshot build from repository: https://oss.sonatype.org/content/repositories/snapshots/

Regards
