### ISSUE TITLE
description of RETRY_INTERVAL & MAX_RETRIES

### ISSUE THREAD

**Issue by mehrdad2000** [influxdata/influxdb-client-java#756]
Hi
Would you please explain what is the meaning of this two parameters:

```
client/src/main/java/com/influxdb/client/WriteOptions.java
    public static final int DEFAULT_RETRY_INTERVAL = 5000;
    public static final int DEFAULT_MAX_RETRIES = 5;
```

1-5000  second or milisecond?
2-try 5 times in row then after 5000 second do this again and again?
3-each 5000 second try one time, do this 5 time and will not retry anymore?

Thanks

**Comment by bednar** [comment]
Hi @mehrdad2000,

the parameters are described in JavaDoc and README:

<img width="1070" alt="image" src="https://github.com/user-attachments/assets/9c380bf0-807e-4b79-9dc9-fa3c8e2520ee">

https://github.com/influxdata/influxdb-client-java/tree/master/client#asynchronous-non-blocking-api

Best Regards

**Comment by mehrdad2000** [comment]
@bednar thanks for answer.
After 5 time retry it will stop trying? Right?
Is there anyway to set parameters in somehow that trying until it will connect? And it’s not stop trying?

**Comment by bednar** [comment]
> @bednar thanks for answer. After 5 time retry it will stop trying? Right? 
Yes.
> Is there anyway to set parameters in somehow that trying until it will connect? And it’s not stop trying?
You can set `maxRetries` to vary large number together with `maxRetryDelay`.
