### ISSUE TITLE
How to combine the privot() and count() functions？

### ISSUE THREAD

**Issue by ZiyRims** [influxdata/influxdb-client-java#768]
What should I do to obtain the total number of records converted by the privot() function?

![image](https://github.com/user-attachments/assets/f175bc80-6a8c-480d-9ee1-1ede3e56a0eb)

**Comment by bednar** [comment]
Hi @ZiyRims,

please take a look to `count` function documentation. You should probably set correct value for `column` parameter.

- https://docs.influxdata.com/flux/v0/stdlib/universe/count/#parameters

Best Regards
