### ISSUE TITLE
Cannot dump measurements into specific database

### ISSUE THREAD

**Issue by BenjaminLeg** [influxdata/influxdb-client-java#84]
Hi,

I was trying to use the spring influxdb client to store data directly inside a specific database.

After struggling for hours I went through the source code and I cannot find a way to set a specific database to dump data inside.

I see we can set bucket, organisation etc... But nothing is possible for selecting a database. I'd like to do like a curl -i -XPOST 'http://localhost:8086/write?db=atlantis'.

Am I mistaken here or is it really not possible to do this with this client ?

Best Regards

**Comment by russorat** [comment]
@BenjaminLeg thanks for the issue. This library is for working with the latest InfluxDB 2.0, which has a different interface than the existing 1.x line. See https://v2.docs.influxdata.com/v2.0/reference/key-concepts/ for an explination of key concepts. 

If you need the 1.x java library, it lives here for now: https://github.com/influxdata/influxdb-java but the long term goal would be to consolidate all that capability into a single library.

**Comment by russorat** [comment]
Please join us on our Community Slack https://influxdata.com/slack if you have more questions.

**Comment by BenjaminLeg** [comment]
Thanks a lot for your return !
