### ISSUE TITLE
@Column does not support super class inheritance

### ISSUE THREAD

**Issue by mikhaildudin-work** [influxdata/influxdb-client-java#89]
Same as [here](https://github.com/influxdata/influxdb-java/issues/367)

Mapper does not check for `@Column` annotated fields in super class, thus, "column" fields from super class does not appear in resulting measurement obj.

**Comment by bednar** [comment]
Hi @mikhaildudin-work,

Thanks for issue. We will fix it in [1.6.0](https://github.com/influxdata/influxdb-client-java/milestone/9) milestone.

Regards

**Comment by bednar** [comment]
Hi @mikhaildudin-work,

The issue is fixed in [1.6.0 milestone](https://github.com/influxdata/influxdb-client-java/milestone/9). 

If you would like to use a preview version use our snapshot build from repository: https://oss.sonatype.org/content/repositories/snapshots/

Regards
